<h1>What Is Aspiration Raising All About?</h1>

<p>

In September 2001 the <a href="http://www.cam.ac.uk/">University of Cambridge</a> was allocated three years of funding from the <a href="http://www.hefce.ac.uk/">Higher Education Funding Council for England</a> (HEFCE). This was to enable the university to enhance its existing strategy for raising aspirations, and widening participation and access, by further developing and strengthening its relationships with schools, sixth-form colleges and further education institutions involved in the <a href="http://www.standards.dfes.gov.uk/excellence/">Excellence in Cities</a> (EiC), <a href="http://www.standards.dfes.gov.uk/eaz/">Education Action Zones</a> (EAZ) and <a href="http://www.dfes.gov.uk/aimhigher/">AimHigher</a> programmes.

</p>

<p>
Building on the success of the <a href="http://www.mmp.maths.org/"> Millennium Maths Project</a>, initial funding was also provided for an ambitious initiative: the provision of five new, wholly web-based, outreach projects for use by students and teachers in schools and colleges. 
</p>

<p>

In February 2002, the university's <a href="http://www.caret.cam.ac.uk/">Centre for Applied Research in Educational Technologies</a> (CARET) was one of eight departments awarded aspiration-raising funds to assist the University of Cambridge deliver its aspiration-raising agenda as part of its widening participation and access programme by July 2004. Three of the new web-based projects have been developed by CARET:

</p>

<ul>

<li>Brainteasers and Puzzles (cross-curricular thinking skills)</li>
<li>rEvolution (natural sciences) </li>
<li>Human Factory (human anatomy and biology)</li>

</ul>

<p>

The purpose of all the aspiration-raising projects is to encourage and inspire 11-19 year olds - in particular, those with low or no aspirations and without a background or tradition in further or higher education - to consider studying at a further and/or higher education level as a worthwhile investment in their future.

</p>

<p>

The resources being developed are designed to complement the national curriculum, and challenge and engage the target groups in a learning process that raises their achievements.

</p>