<h1>About Brainteasers and Puzzles</h1>

<h2>The Vision</h2>

<p>

To support and encourage young people in their aspirations to aim higher by developing a collection of brainteasers and puzzles designed to appeal to all styles and methods of learning; and to give learning an extended dimension while allowing it to be 'cool' and fun. Thereby turning a subject previously conceived as dry and boring, into a potential career development a young person aspires to.

</p>

<h2>The Brief</h2>

<p>

To create, implement and deliver a collection of interactive brainteasers and puzzles comprising a range of problem-solving genres including intuitive, cognitive, logic, scenario-based and role-play; and spanning a diverse spectrum of disciplines.

</p>

<h2>The Aim</h2>

<p>

To stimulate, develop and strengthen the transferable thinking skills of of 11-18 year olds by 'exploiting' their natural curiosity and ability to explore and question; and to provide a resource enabling them to create their own framework of understanding and learning - to challenge and extend their thinking and problem-solving skills through gathering, assimilating and applying newly-acquired information to different scenarios.

</p>

<h2>The Methodology</h2>

<p>

The primary source of external experience and expertise for the Brainteasers and Puzzles team has been teachers, parents and students from secondary schools and sixth-form colleges, and teacher trainees from the university's Faculty of Education PGCE course.

</p>

<p>

This has been in the form of small focus groups held at CARET and pilots run in schools using the potential end users to contribute to the final product. Through collaborating with <a href="http://www.admin.cam.ac.uk/offices/admissions/">Cambridge Admissions Office</a> (CAO), and through the College/LEA existing links, the <a href="http://www.standards.dfes.gov.uk/excellence/">Excellence in Cities</a> (EiC) and <a href="http://www.standards.dfes.gov.uk/eaz/">Education Action Zones</a> (EAZ) programmes, and the <a href="http://www.specialistschoolstrust.org.uk/">Specialist Schools Trust</a> the team were able to identify relevant target audiences to assist with the development process.

</p>

<p>
On teachers' requests, we did not work with just gifted and talented students, but also with lower ability and disaffected students across the UK, in a variety of settings from state of the art City Learning Centres to classrooms with the absolute minimum technical requirements. Reports on sessions can be found under Behind the Scenes in Focus Group Findings.

</p>

