<h1>Acknowledgements</h1>

<div style="text-align:center">

<p>

<b>The Brainteasers and Puzzles team would like to thank:</b>
</p>

<p>
All the schools, individual students and teachers, and Gifted and Talented co-ordinators <br />
who have contributed to the ongoing development of the project
</p>

<p>
University of Cambridge Aspiration-raising Steering Group<br />
Professor Peter Goddard, Dr David Livesey, Susan Stobbs and Janet Graham
</p>

<p>
Katharine Hartley<br />
Project Leader for rEvolution, natural sciences aspiration-raising project
</p>

<p>
Harriet Truscott<br />
Project Leader for converse, the English aspiration-raising literature project
</p>

<p>
Rosemary Butcher<br />
Gifted &amp; Talented / AimHigher Co-ordinator (Secondary), Lambeth Excellence in Cities
</p>

<p>
Sharon Warren and Emer Scott<br />
University of Cambridge Press and Access Officers
</p>

<p>
Ted Krawec<br />
University of Cambridge Research Services Division
</p>

<p>
Mike Sheridan<br />
Gifted and Talented Co-ordinator for Lewisham
</p>

<p>
Janet Waters<br />
Head of Curriculum Support, Specialist Schools Trust
</p>

<p>
Paul Marsden<br />
Eastern Region Co-ordinator, Specialist Schools Trust
</p>

<p>
Stephen Grundy<br />
HE Officer, Specialist Schools Trust
</p>

<p>
University of Cambridge College/LEA Link Officers
</p>

<p>
and of course<br />
</p>

<p>
CARET<br />
University of Cambridge's Centre for Applied Research in Educational Technologies
</p>


</div>