<h1>Other Contributors</h1>

<p>

<b>Christian Baekkelund:</b> <i>provided the initial concepts for the Trebuchet and Bomb puzzles</i>
</p>

<p>
A computer science and media studies student at <a href="http://www.mit.edu/" >MIT</a> (Massachusetts Istitute of Technology, USA), Christian Baekkelund spent a fleeting six weeks with the team before going back to Cambridge, Massachusetts, to do an MA with the Institute. In computer science, Christian studied computer graphics and artificial intelligence; he has also worked for several organisations including Avid, Electronic Arts and the MIT Media Lab, doing research, design and programming related tasks.
</p>

<p>
<b>Drew Buddie:</b> <i>researched, designed and wrote the teachers' handbook</i>
</p>

<p>
Drew Buddie is the ICT Co-ordinator at the Royal Masonic School for Girls in Rickmansworth. Drew is particularly interested in using ICT in innovative ways to support the work pupils do in other subjects.
</p>

<p>
<b>Mei-Fang Chou:</b> <i>provided the initial concept for the Inuit game in the Know Your Earthling puzzle</i>
</p>

<p>
During her short stay in Cambridge Mei-Fang Chou worked as a freelance puzzle developer for the project. Mei-Fang received an MA in 3D character animation from the Academy of Art College, San Francisco, and a BA in commercial design from Chung Yang Christian University, Taiwan. Mei-Fang's professional experience includes being a 3D animator for Global Broadcasting Co. Ltd, Taiwan, an assistant animator and a graphic designer for other commercial companies in her home country of Taiwan to where she has now returned.
</p>

<p>
<b>Jacqui Gaiser-Porter:</b> <i>advised on, and provided text for, the biology puzzles</i>
</p>

<p>
Jacqui Gaiser-Porter grew up in Lancashire and studied Botany in Nottingham. After gaining her degree, and spending quite a few holidays working with young people, Jacqui decided that she wanted to teach and, hence, spent another year in Nottingham doing a PGCE. Following that Jacqui took a post in Hunstanton, then moved to Hull. In 1992 she moved to Cambridge to be Head of Biology at Netherhall School. Jacqui worked there until the summer of 2001, at which point she decided to take a career break to spend time with her two young sons, then aged one and three. Since then Jacqui has worked for <a href="http://www.ocr.org.uk/OCR/WebSite/docroot/index.jsp" >OCR</a> in a consultancy capacity and also teaches part-time at the Ida Darwin Hospital.
</p>

<p>
<b>Zina Foster-Brown, Sarah Hunt and Mackenzie Millar:</b> <i>provided the original ideas for the Bungee puzzle</i>
</p>

<p>
These three students came up with the idea for Bungee during a puzzle workshop held with a group of Year 9 girls at Levenshulme High School in Manchester.
</p>

<p>
<b>Katie Hawks:</b> <i>provided the initial concept and content information for the Shields of Honour puzzle</i>
</p>

<p>
Katie read History at the University of St Andrews, and is currently completing a Ph.D. on medieval heraldry at the University of Cambridge.  She is also doing a P.G.C.E., and is very much enjoying inflicting History on secondary school pupils.
</p>

<p>
<b>Laurence Marco:</b> <i>provided the quality assurance for the Tour de France puzzle </i>
</p>

<p>
Laurence has been living in England for the past five years. She has studied languages as well as having a background in law. After obtaining a teaching diploma from Cambridge she decided to stay here and gain experience in a variety of jobs. She has enjoyed translating different texts for learning purposes and is thinking of launching into that field.
</p>

<p>
<b>Carrie Walsh:</b> <i>advised on, and provided the text for, the physics puzzles</i>
</p>

<p>
Carrie Walsh was a reseach scientist at the University of Cambridge for 16 years, working in both physics and materials science, and specialising in electron microscopy and spectroscopy. During this time she gained some experience of teaching at undergraduate and postgraduate level. Carrie has since  moved on to other pastures.
</p>

