<h1>Copyright Notice</h1>

<p>The material on this site must not be reproduced in any medium without the permission of the appropriate copyright holder.</p>
<p>Unless otherwise stated, the copyright of all resources, including the handbook and the puzzles, belongs to their creators, CARET (the Centre for Applied Research in Educational Technologies), and the University of Cambridge.</p>
<p>Permission has been sought from, and given by, appropriate copyright holders where their material has been used for puzzles. Acknowledgement and copyright details can be found under Acknowledgements, and users wishing to use any of this material will need to seek permission directly from the relevant source.</p>
<p>Teachers and students are welcome to download and make one copy each of the material for use in teaching or studying. An acknowledgement of the source should be included whenever material from this site is copied or referred to.</p>
<p>Users must not republish any part of the data either on another website, or in any other medium, print, electronic or otherwise, or as part of any commercial service without prior written permission.
</p>
