<a name="top"></a>

<h1>Privacy Policy</h1>

<p>

The following statement explains the University of Cambridge's Centre for Applied
Research in Educational Technologies' <strong>Brainteasers and Puzzles</strong>
policy regarding the personal information it collects about you.

</p>


<ol>

<li><a href="#1">Statement of intent</a></li>
<li><a href="#2">Information on visitors</a></li>
<li><a href="#3">What is a cookie?</a> </li>
<li><a href="#4">Submitting personal information</a></li>
<li><a href="#5">Access to your personal information</a></li>
<li><a href="#6">Users 16 and under</a></li>
<li><a href="#7">How to find and control your cookies</a></li>
<li><a href="#8">How do you know which sites use cookies?</a></li>
<li><a href="#9">How to see your cookie code</a></li>
<li><a href="#10">On-line questionnaires</a></li>
<li><a href="#11"> Follow-up emails</a></li>
<li><a href="#12"> Amendments to policy</a></li>

</ol>

<a name="1"></a><h2>1. Statement of intent</h2>

<p>
  From time to time, you will be asked to submit personal information about yourself
  (e.g. name and email address etc) in order to receive or use services on our
  website. Such services may include competitions, message boards, etc. </p>
<p>By entering your details in the fields requested, you enable the University
  of Cambridge's Centre for Applied Research in Educational Technologies (CARET)
  to further develop and improve its website and the content contained on it.
  Whenever you provide such personal information, CARET will treat that information
  in accordance with this policy. CARET will act in accordance with current legislation
  and aim to meet current Internet best practice. </p>

<a name="2"></a><h2>2. Information on visitors</h2>

<p>
  During the course of any visit to <strong>Brainteasers and Puzzles</strong>,
  the pages you see, along with something called a cookie, are downloaded to your
  computer (see point 3 for more on this). Most, if not all, websites do this,
  because cookies allow the website publisher to do useful things like find out
  whether the computer (and probably its user) has visited the site before. This
  is done on a repeat visit by checking to see, and finding, the cookie left there
  on the last visit. </p>
<p>Any information that is supplied by cookies can help us to provide you with
  information and puzzles specific to your needs. It also assists us to analyse
  the profile of our visitors. For example: if on a previous visit you played,
  for example, all the physics-based puzzles, then we might find this out from
  your cookie and highlight physics student or teacher on a second visit. </p>
<p>As part of the project's monitoring and evaluation process, CARET gathers non-personal
  data regarding the visitors to <strong>Brainteasers and Puzzles</strong> using
  cookies and code which is embedded in the site. Both the cookies and the embedded
  code provide non-personal statistical information about visits to pages on the
  site, the duration of individual page view, paths taken by visitors through
  the site, data on visitors' screen settings and other general information. CARET
  uses this type of information, as with that obtained from other cookies used
  on the site, to help it improve and develop resources on the site. </p>

<p><small><a href="#top">[Top]</a></small></p>


<a name="3"></a><h2>3. What is a cookie?</h2>

<p>
  When you enter a site your computer will automatically be issued with a cookie.
  Cookies are text files that identify your computer to our server. Cookies in
  themselves do not identify the individual user, just the computer used. Many
  sites do this whenever a user visits their site in order to track traffic flows.
</p>
<p>Cookies themselves only record those areas of the site that have been visited
  by the computer in question, and for how long. Users have the opportunity to
  set their computers to accept all cookies, to notify them when a cookie is issued,
  or not to receive cookies at any time. The last of these, of course, means that
  certain areas of the site cannot be fully accessed by that user. </p>


<a name="4"></a><h2>4. Submitting personal information</h2>

<p>
  When you supply any personal information to CARET (e.g. for competitions, messageboards,
  etc.) we have legal obligations towards you in the way we deal with that data.
  CARET must collect the information fairly, that is, it must explain how it will
  use it and tell you if we want to pass the information on to anyone else. In
  general, any information you provide to CARET will only be used within CARET
  and possibly relevant departments and personnel within the University of Cambridge.
  Information will never be supplied to anyone outside the University of Cambridge
  without first obtaining your consent, unless we are obliged or permitted by
  law to disclose it. Also, if you post or send offensive or inappropriate content
  anywhere on or to Brainteasers and Puzzles and CARET considers such behaviour
  to be serious and/or repeated, CARET can use whatever information that is available
  to it about you to stop such behaviour. This may include informing relevant
  third parties such as your employer, school or e-mail provider about the content
  and your behaviour. </p>
<p>CARET will ensure that all personal information supplied is held securely,
  in accordance with the Data Protection Act 1998. </p>
<p>CARET will not contact you for promotional purposes, such as notifying you
  of improvements or new developments on <strong>Brainteasers and Puzzles</strong>
  unless you specifically agree to be contacted for such purposes at the time
  you submit your information on the site, or at a later time if you sign up specifically
  to receive such information.</p>


<p><small><a href="#top">[Top]</a></small></p>


<a name="5"></a><h2>5. Access to your personal information</h2>

<p>
  You have the right to request a copy of the personal information CARET holds
  about you and to have any inaccuracies corrected. (CARET charges &pound;10 for
  information requests.) Please address requests to the Brainteasers and Puzzles,
  CARET, 1st Floor, 16 Mill Lane, Cambridge CB2 1SB (Email: puzzling@caret.cam.ac.uk).
</p>

<a name="6"></a><h2>6. Users 16 and under</h2>

<p>
  If you are aged 16 or under, please get your parent/guardian's permission beforehand
  whenever you provide personal information to the <strong>Brainteasers and Puzzles</strong>
  website. Users without this consent are not allowed to provide us with personal
  information. </p>

<a name="7"></a><h2>7. How to find and control your cookies</h2>

<h3>If you're using Netscape 7.0:</h3>
<ol>
  <li> On your Task Bar, click Edit, then</li>
  <li> Preferences</li>
  <li> Click on Privacy and Security</li>
  <li> Click on Cookies</li>
</ol>

<h3>If you're using Netscape 6.0:</h3>
<ol>
  <li> On your Task Bar, click Edit, then</li>
  <li> Preferences</li>
  <li> Click on Advanced</li>
  <li> Click on Cookies</li>
</ol>

<h3>If you're using Internet Explorer 6.0:</h3>
<ol>
  <li>Choose Tools, then </li>
  <li> Internet Options</li>
  <li> Click the Privacy Tab</li>
  <li> Click on Custom Level</li>
  <li> Click on the 'Advanced' button </li>
  <li> Check the 'override automatic cookie handing' box and select Accept, Block
  or Prompt for action as appropriate.</li>
</ol>

<h3>If you're using Internet Explorer 5.0 or 5.5:</h3>
<ol>
  <li>Choose Tools, then</li>
  <li> Internet Options</li>
  <li> Click the Security tab</li>
  <li> Click on Custom Level</li>
  <li> Scroll down to the sixth option to see how cookies are handled by IE5 and
  change to Accept, Disable, or Prompt for action as appropriate.</li>
</ol>

<h3>If you're using Internet Explorer 4.0:</h3>
<ol>
  <li>Choose View, then</li>
  <li> Internet Options</li>
  <li> Click the Advanced tab</li>
  <li> Scroll down to the yellow exclamation icon under Security and choose one
  of the three options to regulate your use of cookies.</li>
</ol>

<h3>If you're using Internet Explorer 3.0:</h3>
<p>
  You can View, Options, Advanced, then click on the button that says Warn before
  Accepting Cookies.</p>

<h3>If you're using Netscape Communicator 4.0:</h3>
<ol>
  <li> On your Task Bar, click Edit, then</li>
  <li> Preferences </li>
  <li> Click on Advanced</li>
  <li> Set your options in the box that says Cookies.</li>
</ol>


<p><small><a href="#top">[Top]</a></small></p>


<a name="8"></a><h2>8.  How do you know which of the sites you've visited use cookies?</h2>
<h3>If you're using Netscape 6.0:</h3>
<ol>
  <li> On your Task Bar, click Edit, then</li>
  <li> Preferences </li>
  <li> Click on Advanced</li>
  <li> Click on Cookies </li>
  <li> Click the View Cookies button</li>
</ol>

<h3>If you're using Internet Explorer 5.0 or 6.0:</h3>
<ol>
  <li> Choose Tools, then</li>
  <li> Internet Options</li>
  <li> Click the General tab </li>
  <li> Click Settings </li>
  <li> View Files</li>
</ol>

<h3>If you're using Internet Explorer 4.0:</h3>
<ol>
  <li> On your Task Bar, click View, then</li>
  <li> Internet Options</li>
  <li> Under the tab General (the default tab) click</li>
  <li> Settings</li>
  <li> View Files</li>
</ol>

<h3>Internet Explorer 3.0:</h3>
<ol>
  <li> On your Task Bar, click View</li>
  <li> Options</li>
  <li> Advanced</li>
  <li> View Files</li>
</ol>

<h3>Netscape Communicator 4.0:</h3>
<p>
  Netscape bundles all cookies into one file on your hard drive. You'll need to
  find the file, which it calls Cookie.txt on Windows machines.</p>


<p><small><a href="#top">[Top]</a></small></p>

<a name="9"></a><h2>9. How to see your cookie code</h2>

<p>
  Just click on a cookie to open it. You'll see a short string of text and numbers.
  The numbers are your identification card, which can only be seen by the server
  that gave you the cookie. </p>


<a name="10"></a><h2>10. On-line questionnaires</h2>
<p>
  From time to time, an option to complete an on-line questionnaire will pop-up.
  This allows Brainteasers and Puzzles to undertake a more effective evaluation
  than cookies allow. By completing a questionnaire, you automatically agree to
  CARET using the information for statistical purposes. No personal information
  will be given out or revealed without prior written consent from you. The information
  that is useful for assessing the value of a project such as Brainteasers and
  Puzzles as a teaching and learning resource includes postcodes, ages, gender,
  school, whether you worked individually or collaboratively on certain puzzles,
  and why puzzles engaged or did not engage you.</p>

<a name="11"></a><h2>11. Follow-up email</h2>
<p>
  If you have given a particularly interesting response on the questionnaire,
  CARET may wish to follow up with an email to quantify what you have written.
  This information is likely to only be used for puzzle improvement and development
  purposes. If CARET wishes to use the information collected for any other purposes,
  it will only do so with prior written consent from you. You will of course be
  given the option to not receive a follow-up email on the questionnaire.</p>

<a name="12"></a><h2>12. Amendments to policy</h2>
<p>
  The <strong>Brainteasers and Puzzles Privacy Policy</strong> is subject to change
  at any time. CARET encourages you to review the privacy policy regularly for
  any changes.</p>

<p>
 <small><a href="#top">[Top]</a></small>
<!--
 <a href="index.php?section=ageselect">Back</a> -->
</p>