<h1>Sites to Look at</h1>

 <h2>Other Puzzle Sites to Visit:</h2>

<ul>

 <li>
 <a href="http://www.channel4.com/learning">4learning</a>
 </li>

 <li>
 <a href="http://www.bbc.co.uk/schools/aimhigher/games/index.shtml">AimHigher</a>
 </li>

 <li>
 <a href="http://www.daniel-powell.demon.co.uk">Ashfield Science</a>
 </li>

 <li>
 <a href="http://www.bbc.co.uk/schools/gcsebitesize/">BBC Bitesize</a>
 </li>

 <li>
 <a href="http://www.bbc.co.uk/games/braingames/index.shtml">BBC Brain Games</a>
 </li>

 <li>
 <a href="http://www.bbc.co.uk/history/multimedia_zone/games/index.shtml">BBC History</a>
 </li>

 <li>
 <a href="http://www.bbc.co.uk/nature/blueplanet/">BBC Nature</a>
 </li>

 <li>
 <a href="http://www.open2.net/science/roughscience/where/where_index.htm">BBC Science</a>
 </li>

 
 <li>
 <a href="http://www.ph.bham.ac.uk/prospective/schools/puzzles/index.htm">Birmingham University</a>
 </li>

 <li>
 <a href="http://www.at-bristol.org.uk/Education/nesta/default.htm">Bristol Brain Games</a>
 </li>

 <li>
 <a href="http://www.caret.cam.ac.uk/english">Converse</a>
 </li>

<li>
 <a href="http://www.caret.cam.ac.uk/humanfactory">Human Factory</a>
 </li>

 <li>
 <a href="http://www.nrich.maths.org/">NRICH</a>
 </li>

 <li>
 <a href="http://www.seekscience.org/">SeeK</a>
 </li>

 <li>
 <a href="http://www.mcs.surrey.ac.uk/Personal/R.Knott/Fibonacci/fib.html">The Puzzling World of Fibonacci</a>
 </li>

 <li>
 <a href="http://195.157.98.114/insideout/anatomy/skeleton_territory/index.html">The Royal Institute of GB Science Inside Out</a>
 </li>

 <li>
 <a href="http://www.thestone.com">The Stone</a>
 </li>

 <li>
 <a href="http://revolution.caret.cam.ac.uk/">rEvolution</a>
 </li>

</ul>

 <h2>Other Useful Links</h2>

<ul>

 <li>
 <a href="http://www.dfes.gov.uk/aimhigher/">AimHigher</a>
 </li>

 <li>
 <a href="http://www.hero.ac.uk/studying/index.cfm">HERO</a>
 </li>

 <li>
 <a href="http://www.deni.gov.uk/students/index.htm">Department of Education (N. Ireland)</a>
 </li>

 <li>
 <a href="http://www.bbc.co.uk/learning/colleges/">BBC 16+</a>
 </li>

 <li>
 <a href="http://www.dfes.gov.uk/studentsupport/students/index.shtml">Student Support</a>
 </li>

 <li>
 <a href="http://www.bbc.co.uk/radio1/onelife/education/index.shtml">BBC Radio 1 Onelife</a>
 </li>
</ul>


<br/>

<p>
Disclaimer: Please be advised that neither CARET nor the University of Cambridge guarantee, in any way whatsoever, the validity of the information found in the above links. Neither CARET nor the University of Cambridge represent or endorse in any way, the accuracy or reliability of any of the information or content contained on, distributed through, or linked, downloaded or accessed from any of the above links, nor the quality of any information or other materials displayed, purchased, or obtained by you as a result of an advertisement or any other information or offer in or in connection with the above links.
</p>