<h1>Welcome!</h1>

<p>Welcome to the University of Cambridge's Brainteasers and Puzzles website.</p>

<p>We have created a collection of brainteasers and puzzles that we hope will give you hours of fun, stretching your thinking skills and problem-solving abilities, in the quest to reach the end. There is also one puzzle that originated from a puzzle workshop run with a group of Year 9 girls at Levenshulme High School in Manchester - can you work out which one it is!</p>

<p>The secret to completing these puzzles successfully depends on your ability to apply the appropriate thought processes to the various puzzles. For some puzzles you will rely on intuition - a hunch - to help you, others you will need to draw on your cognitive powers (existing knowledge), some will require logic - principles of reasoning, while others will demand you put your lateral - opposite to logic - thinking hat on, and then there are those that will require you to read and apply information.</p>

<p>Each and every puzzle is different, and there is an explanation for each one that will help you to get the maximum fun and value from them. So, if after two or three attempts you are getting frustrated because you seem to be going nowhere fast, you will find that all-important clue in the instructions!</p>

<p>The puzzles span a wide age range so we have divided them into two groups. Where there is an option for either age group, we have been advised the puzzle is suitable for the complete age range given differing levels of ability, but the text for some of the science-based ones is slightly different and aimed specifically at that age group. A small number of puzzles have one of the age selection buttons shaded out, this means that the puzzle has been developed with only one age range in mind, but that does not preclude the other age group from playing it, of course! </p>

<p>The puzzles also contain additional information that can be used to help extend your knowledge base and, hopefully inspire you to seek even further afield for more information.</p>

<p>So, thinking caps on, good luck and have fun.</p>

<p>Oh, and what is the difference between a brainteaser and a puzzle? That's for you to solve!</p>