<div align="left">


<h2>Adam Sedgwick</h2>
<div>

<img src="images/photos/sedgwicksmall.jpg" align="left" alt="Adam Sedgwick" style="padding-right: 10px">

The Sedgwick museum of geology at the University of Cambridge which houses one
of the largest and most important collections of fossils and minerals in the world
was named as a fitting tribute and memorial to the lifelong work of the geologist
Adam Sedgwick.<br>
</div>
<h3>But who was Adam Sedgwick?</h3>
Sedgwick was born in The Yorkshire Dales in 1785 and at the age of eighteen
  came to study Mathematics at Trinity College Cambridge. Although a gifted mathematician,
  Sedgwick moved into the field of geology, a subject he dabbled in and was given
  a 'chair'(fancy term for becoming a lecturer) in this subject at
  the age of 33, in 1818. From this point on, Sedgwick was addicted to his new
  subject, geology and spent the summer months surveying the rock strata across
  much of Britain. It was this meticulous work that lead to Sedgwick describing
  the Cambrian system; the period of the earth's history from 570- 515 million
  years ago.
  <br>
  <br>
As well as being a great scientist, Sedgwick's other passion was religion.
  His father was the local vicar in his home village of Dent in Yorkshire and
  following in his father's footsteps, Adam Sedgwick took a position as
  a 'canon' at Norwich Cathedral in 1834. From thence, Sedgwick began
  a life where he divided his work into two areas, scientific and ecclesiastical.
  He spent several months a year in Norwich, engulfed in his duties with the church
  and the remaining time engulfed in his scientific studies. But how did he reconcile
  the two sides to his life and indeed the issue of evolution? Sedgwick's
  religion led him to believe that humans and indeed all other species were created
  by God. His understanding of geology showed how new species successively arose
  and died out. To Sedgwick, each species was the product of God's work
  and had a distinct purpose, even if it had become extinct.
  <br>
  <br>
Sedgwick was greatly admired for his passion for and ability in teaching science.
  He strove to reform the British education system and develop scientific curriculums
  at universities. He was a popular public speaker and attracted large audiences
  whether academic or the lay public. He was also a great believer in encouraging
  the work of amateur scientists and collaborated with many to acquire a vast
  number of specimens to vastly develop the geology museum at Cambridge. Sedgwick
  remained a fellow of Trinity College in Cambridge until his death in 1873 at
  the age of 88. <br>
&nbsp;<br>
<a href="index.php?section=scientists">Back</a>


</div>