<h1>Articles</h1>

Here you will find some longer articles written by the rEvolution team. More will be added in the near future, so keep on coming back.

<ul class="dinohand">

<li><a href="pdfs/article_fossil1.pdf">Making your own collection of fossils, part 1</a> - Helen writes about one of the loves of her life - hunting for fossils. Here she gives the low-down on how to start excavating.</li>

<li><a href="pdfs/article_birds1.pdf">Birdwatching, part 1</a> - Helen on how to make the most of one of the most diverse habitats around - your own back garden.</li>

<li><a href="pdfs/article_kiwifruit.pdf">Extracting DNA from a Kiwifruit</a> - The easiest way to get a grip on DNA.</li>
</ul>

<b>Note:</b> These articles are in PDF (Adobe Acrobat) format. If you haven't got Adobe Acrobat, then <a href="http://www.adobe.com/products/acrobat/readstep2.html">download the reader</a>.