<h1>Bookshelf</h1>

<p>Science has become extremely popular over the last twenty or so years, and there are now a lot of resources out there that you can look at for fun, to find something out or just to pass away a rainy weekend. We have listed some of our favourite books, magazines and other resources on this page as a start - why not use the feedback form to tell us of anything else you particularly like? We will add it to this page for everyone to share with you!</p>

<p>We have given a link to a site where you can buy books on our list or subscribe to magazines online. However, we do not endorse any of the sites mentioned in this section of rEvolution, and cannot guarantee the prices quoted. If you have problems, let us know.</p>

<h2>Books</h2>

<a href="http://www.amazon.co.uk/exec/obidos/ASIN/0007137168/ref=ase_uksafari/026-6710840-4550042 ">Wild Guide: British Wildlife</a><br>
	Published by Collins (April 2002)<br>
	ISBN: 0007137168<br>
	Price: approx &pound;13.00<br>
<br>
A comprehensive beginner's guide to the wildlife of the British Isles. Maps, photos and even calendars help the amateur to discover over 500 species, and the individual fact files provide information about each species. A lovely way to get started.<br>
<br>

<a href="http://www.amazon.co.uk/exec/obidos/ASIN/0198507968/ref=pd_sxp_elt_l1/026-6710840-4550042">Animal tracks and signs (a Natural History Pocket Guide)</a><br>
Published by Oxford University Press (June 2001)<br>
ISBN: 0198507968<br>
Price: approx &pound;15.00 (hardback)<br>
<br>
Going out looking for elusive wildlife? Take this invaluable book with you and spot the hidden signs of life in the countryside. With practice, you will be able to discover evidence of wildlife you usually wouldn't think lived near you. A brilliant new edition of a book that has been loved for many years by amateur wildlife sleuths.<br>
<br>
<a href="http://www.amazon.co.uk/exec/obidos/ASIN/1856193772/ref=pd_bxgy_img_2_cp/026-6710840-4550042">Flora Britannica</a><br>
Published by Sinclair Stevenson (October 1996)<br>
ISBN: 1856193772<br>
Price: approx &pound;30.00 (hardback)<br>
<br>
An amazingly comprehensive guide to the plants of the British Isles. Everything you have ever wanted to know about UK plants is in here - where are they found, what they look like throughout the year (including seeds, flowers, and leaves) and how do you identify them. If you have any interest in plants at all, this book is the first you ought to buy. If you don't get excited about plants, then it is worth buying just for the pictures.<br>
<br>
A companion book - British Fauna - deals with the animals of the UK in the same comprehensive way (although does tend to concentrate more on vertebrates than invertebrates).<br>
<br>
<a href="http://www.amazon.co.uk/exec/obidos/ASIN/1843300605/ref=pd_sim_b_dp_5/026-6710840-4550042">Nick Baker's British Wildlife: a Month by Month Guide</a><br>
Published by New Holland Publishers (UK) (March 2003)<br>
ISBN: 1843300605<br>
Price: approx &pound;17.00 (hardback)<br>

<br>
Another way to look at the wildlife around you. This fantastic book takes you through a year in the life of the countryside, giving you tips on what to look out for each year and when to expect migrants, flowers, nest building and so on. A great idea to read this book before venturing out!<br>
<br>
<a href="http://www.amazon.co.uk/exec/obidos/ASIN/1859749607/ref=pd_ecc_rvi_f/026-6710840-4550042">The Wildlife Trust's Handbook of Garden Wildlife</a><br>
Published by New Holland Publishers (UK) (June 2002)<br>
ISBN: 1859749607<br>
Price: approx &pound;15.00 (hardback)<br>

<br>
Another interesting idea - a guide to the wildlife that visits your garden. This means there is no excuse for not taking an interest; sit down with a cup of tea and watch the wildlife come to you. The Wildlife Trusts are committed to making sure our natural heritage is preserved, and a good way to get started is to make sure everyone realises just how much nature we have in the UK - especially in our gardens.<br>
<br>
<a href="http://www.amazon.co.uk/exec/obidos/ASIN/186108188X/ref=pd_sim_b_dp_1/026-6710840-4550042">Creating small habitats in your garden for wildlife</a><br>
Published by Guild of Master Craftsmen (February 2001)<br>
ISBN: 186108188<br>
Price: approx &pound;14.00<br>
<br>
If you can't out to see the countryside, then why not bring it to you? This beautifully illustrated book will help you turn your garden into a nature reserve; start your own conservation effort today!


<h2>Magazines and journals</h2>

<a href="http://www.wildlife-film.com/shop/bbcwildlife.htm">BBC Wildlife magazine</a><br>
This magazine contains so much it is hard to know here to start. How about articles on UK wildlife and nature news in general, a round-up of ecological research across the world, special interviews and life histories of some of the world's leading biologists as well as fantastic photographs, great ideas for places to go and things to do and much, much more.<br>

<br>
Subscription rates: approx &pound;30.00 for a year (12 issues)<br>
<br>
<a href="http://www.newscientist.com/">New Scientist</a><br>
The world's leading popular science and technology magazine. With a new issue out each week, you will always be kept abreast of what is happening in the world of robotics, ecology, genetics, physics, palaeontology, parasitology...<br>

<br>
Subscription rates: approx &pound;120 for a year (52 issues). Special rates for schools and students.<br>
<br>
<a href="https://secure.customersvc.com/servlet/Show?PAGEID=NG07030301&amp;MSCCAMLX=00018">National Geographic magazine</a><br>
One of the oldest scientific institutions in the world, the National Geographical Society has sponsored expeditions for over a hundred years. For much of that time, they have produced a magazine detailing the amazing finds of those expeditions - this has now grown into one of the most beautiful things to ever sit on a bookshelf. This one is for the whole family!<br>
<br>
Subscription rates: &pound;30.00 for a year (12 issues)<br>

<h2>Films</h2>

We've trawled through our archives and come up with the beginnings of a list of films that either have a scientific or natural history theme. They might not all be good films - and some of them are getting very old!
<ul class="dinohand">

<li>The Abyss</li>
<li>Adaptation</li>
<li>AI</li>
<li>The Alien films</li>
<li>Anaconda</li>
<li>Antz</li>
<li>Arachnophobia</li>
<li>Best in Show</li>
<li>A Bug's Life</li>
<li>Congo</li>
<li>Crocodile Hunter: Collision Course</li>
<li>Dante's Peak</li>
<li>Deep Blue Sea</li>
<li>Dinosaur</li>
<li>DNA</li>
<li>Flipper</li>
<li>The Fly</li>
<li>Free Willy</li>
<li>Human Nature</li>
<li>Innerspace</li>
<li>Jurassic Park</li>
<li>Lake Placid</li>
<li>Outbreak</li>
<li>The Relic</li>
<li>Snow Dogs</li>
<li>Twister</li>
</ul>
We would also like to add sections on television series, games, interactive CDs and more so that you always have something to do on a wet day when you can't go out. If you have something to add to this section, why not <a href="index.php?section=contact">drop us a line</a>, and let us know?