<h1>Calendar</h1>

This calendar keeps track of all those events locally and across the world that you might like to celebrate or get involved in. If you know of something that we have missed - use the feedback form or contact us to let us know!<br>

<br>
<a href="http://www.ramsar.org/wwd2004_index.htm">World Wetlands Day</a><br>
2nd February each year<br>
Run by Ramsar<br>

<br>
<a href="http://www.bto.org/">National Nest Box Week</a> <br>
Feb 14th - 21st every year (the tradition is that birds find their breeding partners during this week)<br>
Run by British Trust for Ornithology<br>

<br>
<a href="http://www.unesco.org/water/water_celebrations/">World Day for Water</a><br>
22nd March every year<br>
Run by UNESCO<br>

<br>
<a href="http://www.wildlifetrust.org.uk/urbanwt/html/idcd.html">International Dawn Chorus Day</a> <br>
2nd May 2004 (first Sunday of May every year)<br>
Run by the UK Wildlife Trusts<br>
(2003 event - details for 2004 to follow soon)<br>

<br>
<a href="http://www.nettles.org.uk/">Be Nice to Nettles Week</a><br>
19-28 May 2004<br>

<br>
<a href="http://www.gdrc.org/oceans/oceans-day.html">World Oceans Day</a><br>
8th June 2004<br>
Run by Global Development Resource Centre<br>

<br>
<a href="http://www.abdn.ac.uk/mammal/nmw2003.htm">National Mammal Week</a> <br>
July 3rd - 11th 2004<br>
Run by the Mammal Society<br>

<br>
<a href="http://www.bats.org.uk/">National (and European) Bat Week</a><br>
Last week of August (no date yet for next year)<br>

<br>
<a href="http://www.rspb.org.uk/feedthebirds/index.asp">National Feed the Birds Day</a> <br>
25th October 2003 was the first of these days. Look out for more next year.<br>
Run by RSPB<br>

<br>
<a href="http://www.treecouncil.org.uk/">National Tree Week</a> <br>
26th November - 7th December 2003 - look out for next year's events<br>
Run by The Tree Council<br>

<br>
<a href="http://www.commonground.org.uk/treedress.html">Tree Dressing Day</a><br>
First full weekend in December each year<br>
Run by Common Ground<br>

<br>
<a href="http://www.ltl.org.uk/programmes/programme.asp?PG_ID=8 ">National School Grounds week</a> <br>
Varies slightly each year - check website for dates<br>
Run by the Learning through landscapes trust