<h1>Careers Centre</h1>

<p>This section of the rEvolution site is here to give you some help with choosing
a job or career in a scientific field. But really, it's not as boring as
it sounds!</p>

<ul class="dinohand">

  <li><a href="index.php?section=vids_careers">Sound Bites</a>&nbsp;Interviews with people doing some interesting science-related jobs</li>

  <li><a href="index.php?section=studentstuff">Student Stuff</a>&nbsp;Advice and help on becoming a student - including how to get help with funding, alternative student handbooks, and student survival</li>

  <li><a href="index.php?section=universityinfo">Cambridge University</a>&nbsp;Information about applying to and studying at Cambridge University</li>

</ul>

<p><a href="index.php?section=careersguide">Extra Information for teachers and parents</a></p>