<h2>Careers Centre Guide</h2>

<p>The main aim of this site is to encourage bright pupils from all backgrounds to consider going to University to study science - and in particular the natural sciences - at a degree level. The careers centre provides factual information to help students with the choices that the admission process will throw at them. </p>

<p>The careers centre lists many of the areas in which someone with a science degree may end up working, and provides information to students about further qualifications they may need, what degree would be the best to do for any particular job, what the job really entails and how they can find more information. </p>

<p>This factual information is backed up by a host of recorded interviews with people working in various scientific fields. They talk openly about their school life, what degree they did, how they survived university, how they ended up in the job they are doing and what an average day at work is like. Additional interviews with current Cambridge University students help to give a flavour of what student life is like to those who may be worried about whether they could cope or not.</p>

<p>This section of the site is intended to grow over the years to provide a comprehensive interactive careers resource for students and their families, helping them to make the decisions necessary to enter University and the workplace. Currently the resources available are:</p>

<ul class="dinohand">

<li><a href="index.php?section=careers">Careers Information</a>
This section of the site will grow over time to provide a comprehensive index of career possibilities in the Natural sciences. We aim to provide information about routes into each career, suggestions for voluntary and other work, training needs and - wherever possible - an interview with someone already doing the job. This will give students a chance to review and compare exciting opportunities and listen to real people talk about what they do for a living and so help them to realise the huge world that studying science can open for them.</li>

<li><a href="index.php?section=vids_careers">Videotaped interviews (Sound Bites)</a>
This will be an expanding resource, full of video and audio interviews and diaries centring on people already working in some of the areas that students may be interested in. Accounts of student life will also be included to give prospective students a flavour of what they can expect when they go to university themselves.</li>

<li><a href="index.php?section=universityinfo">University of Cambridge information</a>
This section will provide links to the admissions, careers and departmental webpages of the University of Cambridge (our sponsors). Through these resources, students will be able to get an idea of the scope of a university, what resources they can expect to work with, what sort of work a department does and how the admission process works.</li>

<li><a href="index.php?section=studentstuff">Student information</a>
This slightly less formal section of the careers centre will focus on student life. As the site grows, we will gather in here links to student survival guides, where to go for help, how to apply for grants, links to alternative student handbooks and accounts by real students of what to expect from three years of hard work and serious play.</li>

</ul>

<p>This section will also provide links to general careers resources, such as advice on interview technique, how to write a CV, and much more.</p>