<h2>Flash Checker</h2>

Checking to see if you have Flash installed...

<NOSCRIPT>

<h2>Please Activate Javascript!</h2>

If you are reading this message, it is probably because you do not have JavaScript enabled
in your browser. You must have JavaScript turned on in your browser in order to access rEvolution.<br>

&nbsp;<br>


To enabled JavaScript, in Internet Explorer, select "Internet Options" on the "Tools" menu. Then click on the "Security" tab, and
then the "Custom Level" button. The 'Active Scripting' option on the menu should be set to 'Enabled'.<br>

&nbsp;<br>

If you have enabled Javascript, you can progress to the <a href="index.php?section=museum&template=hc">museum</a>.

</NOSCRIPT>