<h1>Copyright notice</h1>

All information and images on this site are protected by copyright and cannot be copied without permission.

<br>&nbsp;<br>

Copyright &copy; CARET 2003

<br>&nbsp;<br>

All Rights Reserved

<br>&nbsp;<br>

Students and teachers may use the material on this site in project work and for lesson plans without permission. We would ask that credit for the material used be given in these cases.

<a name="disclaimer"></a>

<h1>Disclaimer</h1>

All of the information on this site is provided by us in good faith as an educational service. We have taken every effort to ensure the accuracy of the information contained within this site. However, users of this site who rely on this information do so at their own risk; we cannot be held liable for the consequences of actions or decisions made on the basis of the information herein offered.

<br>&nbsp;<br>

We have linked to many other websites as part of the service that we offer. While we have done our best to ensure that sites we have linked to are suitable for viewing by children and young adults, we are not responsible for the contents or availability of these external sites, and do not necessarily endorse the views expressed within them. We cannot guarantee that these links will continue to be available, and listing within our site is not to be taken as an endorsement of any kind.

<br>&nbsp;<br>

If you find any inaccuracies on this site, or have you have spotted anything that gives you cause for concern, please <a href="index.php?section=contact">contact us</a> in the first instance. We will make every effort to resolve the issue.

<br>&nbsp;<br>

<a name="privacy"></a>
<h1>Privacy Policy</h1>

The following statement explains the University of Cambridge's Centre for Applied
Research in Educational Technologies policy regarding the personal information it collects about you. <br>
<br>
<font size="4">1. &nbsp; <a href="#1">Statement of intent</a><br />
2.  &nbsp; <a href="#2">Information on visitors</a><br />
3.  &nbsp; <a href="#3">What is a cookie?</a> <br />

4.  &nbsp; <a href="#4">Submitting personal information</a><br />
5.  &nbsp; <a href="#5">Access to your personal information</a><br />
6.  &nbsp; <a href="#6">Users 16 and under</a><br />
7.  &nbsp; <a href="#7">How to find and control your cookies</a><br />
8.  &nbsp; <a href="#8">How do you know which sites use cookies?</a><br />

9.  &nbsp; <a href="#9">How to see your cookie code</a><br />
10. <a href="#10">On-line questionnaires</a><br />
11. <a href="#11"> Follow-up emails</a><br />
12. <a href="#12"> Amendments to policy</a></font><br />
<p> <a name="1"><strong><font size="4">1. </font></strong></a><font size="4"><strong>Statement
  of intent</strong></font><strong> </strong><br>

  From time to time, you will be asked to submit personal information about yourself
  (e.g. name and email address etc) in order to receive or use services on our
  website. Such services may include competitions, message boards, etc. </p>
<p>By entering your details in the fields requested, you enable the University
  of Cambridge's Centre for Applied Research in Educational Technologies (CARET)
  to further develop and improve its website and the content contained on it.
  Whenever you provide such personal information, CARET will treat that information
  in accordance with this policy. CARET will act in accordance with current legislation
  and aim to meet current Internet best practice. </p>
<p><a name="2"><strong>2<font size="4">.</font></strong></a><font size="4"><strong>
  Information on visitors </strong></font><br>
  During the course of any visit to <strong>rEvolution</strong>,
  the pages you see, along with something called a cookie, are downloaded to your
  computer (see point 3 for more on this). Most, if not all, websites do this,
  because cookies allow the website publisher to do useful things like find out
  whether the computer (and probably its user) has visited the site before. This
  is done on a repeat visit by checking to see if there is a cookie left there
  on the last visit. </p>
<p>Any information that is supplied by cookies can help us to provide you with
  information and puzzles specific to your needs. It also assists us to analyse
  the profile of our visitors. </p>

<p>As part of the project's monitoring and evaluation process, CARET gathers non-personal
  data regarding the visitors to <strong>rEvolution</strong> using
  cookies and code which is embedded in the site. Both the cookies and the embedded
  code provide non-personal statistical information about visits to pages on the
  site, the duration of individual page view, paths taken by visitors through
  the site, data on visitors' screen settings and other general information. CARET
  uses this type of information, as with that obtained from other cookies used
  on the site, to help it improve and develop resources on the site. <br>
</p>
<p><a name="3"><strong><font size="4">3. </font></strong></a><font size="4"><strong>What
  is a cookie?</strong></font> <br>
  When you enter a site your computer will automatically be issued with a cookie.
  Cookies are text files that identify your computer to our server. Cookies in
  themselves do not identify the individual user, just the computer used. Many
  sites do this whenever a user visits their site in order to track traffic flows.
</p>
<p>Cookies themselves only record those areas of the site that have been visited
  by the computer in question, and for how long. Users have the opportunity to
  set their computers to accept all cookies, to notify them when a cookie is issued,
  or not to receive cookies at any time. The last of these, of course, means that
  certain areas of the site cannot be fully accessed by that user. </p>
<p><a name="4"><strong><font size="4">4.</font></strong></a><font size="4"><strong>

  Submitting personal information</strong></font> <br>
  When you supply any personal information to CARET (e.g. for competitions, messageboards,
  etc.) we have legal obligations towards you in the way we deal with that data.
  CARET must collect the information fairly; that is, it must explain how it will
  use it and tell you if we want to pass the information on to anyone else. In
  general, any information you provide to CARET will only be used within CARET
  and possibly relevant departments and personnel within the University of Cambridge.
  Information will never be supplied to anyone outside the University of Cambridge
  without first obtaining your consent, unless we are obliged or permitted by
  law to disclose it. Also, if you post or send offensive or inappropriate content
  anywhere on or to rEvolution and CARET considers such behaviour
  to be serious and/or repeated, CARET can use whatever information that is available
  to it about you to stop such behaviour. This may include informing relevant
  third parties such as your employer, school or e-mail provider about the content
  and your behaviour. </p>
<p>CARET will ensure that all personal information supplied is held securely,
  in accordance with the Data Protection Act 1998. </p>
<p>CARET will not contact you for promotional purposes, such as notifying you
  of improvements or new developments on <strong>rEvolution</strong>
  unless you specifically agree to be contacted for such purposes at the time
  you submit your information on the site, or at a later time if you sign up specifically
  to receive such information. <br>
</p>

<p><a name="5"><font size="4"><strong>5.</strong></font></a><font size="4"><strong>
  Access to your personal information</strong></font> <br>
  You have the right to request a copy of the personal information CARET holds
  about you and to have any inaccuracies corrected. (CARET charges &pound;10 for
  information requests.) Please address requests to rEvolution,
  CARET, 1st Floor, 16 Mill Lane, Cambridge CB2 1SB (Email: puzzling@caret.cam.ac.uk).
</p>
<p><a name="6"><strong><font size="4">6.</font></strong></a><font size="4"><strong>
  Users 16 and under</strong></font><strong> </strong><br>
  If you are aged 16 or under, please get your parent/guardian's permission beforehand
  whenever you provide personal information to the <strong>rEvolution</strong>
  website. Users without this consent are not allowed to provide us with personal
  information. </p>
<p><a name="7">7<font size="4"><strong>.</strong></font></a><font size="4"><strong>
  How to find and control your cookies </strong></font></p>
<p><em><strong>If you're using Netscape 7.0:</strong></em><br>
  On your Task Bar, click:<br>
  1. Edit, then<br>
  2. Preferences<br>
  3. Click on Privacy and Security<br>
  4. Click on Cookies</p>
<p><em><strong>If you're using Netscape 6.0:</strong></em><br>
  On your Task Bar, click:<br>
  1. Edit, then<br>

  2. Preferences<br>
  3. Click on Advanced<br>
  4. Click on Cookies</p>
<p><em><strong>If you're using Internet Explorer 6.0:</strong></em><br>
  1. Choose Tools, then <br>
  2. Internet Options<br>

  3. Click the Privacy Tab<br>
  4. Click on Custom Level<br>
  5. Click on the 'Advanced' button <br>
  6. Check the 'override automatic cookie handing' box and select Accept, Block
  or Prompt for action as appropriate.</p>
<p><strong><em>If you're using Internet Explorer 5.0 or 5.5:</em></strong><br>
  1. Choose Tools, then<br>

  2. Internet Options<br>
  3. Click the Security tab<br>
  4. Click on Custom Level<br>
  5. Scroll down to the sixth option to see how cookies are handled by IE5 and
  change to Accept, Disable, or Prompt for action as appropriate.</p>
<p><strong><em>If you're using Internet Explorer 4.0:</em></strong><br>
  1. Choose View, then<br>

  2. Internet Options<br>
  3. Click the Advanced tab<br>
  4. Scroll down to the yellow exclamation icon under Security and choose one
  of the three options to regulate your use of cookies. </p>
<p><strong><em>In Internet Explorer 3.0:</em></strong><br>
  You can View, Options, Advanced, then click on the button that says Warn before
  Accepting Cookies. </p>
<p><em><strong>If you're using Netscape Communicator 4.0:</strong></em><br>
  On your Task Bar, click:<br>

  1. Edit, then<br>
  2. Preferences <br>
  3. Click on Advanced<br>
  4. Set your options in the box that says Cookies. <br>
  </p>
<p><a name="8"><strong><font size="4">8.</font></strong></a><font size="4"><strong>

  How do you know which of the sites you've visited use cookies? </strong></font></p>
<p><em><strong>If you're using Netscape 6.0:</strong></em><br>
  On your Task Bar, click:<br>
  1. Edit, then<br>
  2. Preferences <br>
  3. Click on Advanced<br>
  4. Click on Cookies <br>
  5. Click the View Cookies button </p>
<p><strong><em>If you're using Internet Explorer 5.0 or 6.0:</em></strong><br>
  1. Choose Tools, then<br>
  2. Internet Options<br>
  3. Click the General tab <br>
  4. Click Settings <br>
  5. View Files </p>
<p><strong><em>If you're using Internet Explorer 4.0:</em></strong><br>
  On your Task Bar, click:<br>
  1. View, then<br>
  2. Internet Options<br>
  3. Under the tab General (the default tab) click<br>
  4. Settings<br>
  5. View Files. </p>
<p><strong><em>Internet Explorer 3.0:</em></strong><br>
  On your Task Bar, click:<br>
  1. View<br>
  2. Options<br>
  3. Advanced<br>
  4. View Files</p>
<p><em><strong>Netscape Communicator 4.0:</strong></em><br>
  Netscape bundles all cookies into one file on your hard drive. You'll need to
  find the file, which it calls Cookie.txt on Windows machines.<br>
</p>
<p><a name="9"><strong><font size="4">9.</font></strong></a><font size="4"><strong>

  How to see your cookie code</strong></font><br>
  Just click on a cookie to open it. You'll see a short string of text and numbers.
  The numbers are your identification card, which can only be seen by the server
  that gave you the cookie. </p>
<p><a name="10"><strong><font size="4">10.</font></strong></a><font size="4"><strong>
  On-line questionnaires</strong></font><br>
  From time to time, an option to complete an on-line questionnaire may pop-up.
  This allows rEvolution to undertake a more effective evaluation
  than cookies allow. By completing a questionnaire, you automatically agree to
  CARET using the information for statistical purposes. No personal information
  will be given out or revealed without prior written consent from you. The information
  that is useful for assessing the value of a project such as rEvolution as a teaching and learning resource includes postcodes, ages, gender,
  school, whether you worked individually or collaboratively on certain puzzles,
  and why puzzles engaged or did not engage you.</p>
<p><a name="11"><font size="4"><strong>11.</strong></font></a><strong><font size="4">
  Follow-up email</font></strong><br>

  If you have given a particularly interesting response on the questionnaire,
  CARET may wish to follow up with an email to quantify what you have written.
  This information is likely to only be used for puzzle improvement and development
  purposes. If CARET wishes to use the information collected for any other purposes,
  it will only do so with prior written consent from you. You will of course be
  given the option to not receive a follow-up email on the questionnaire.</p>
<p><a name="12"><strong><font size="4">12.</font></strong></a><font size="4"><strong>
  Amendments to policy</strong></font><br>
  The <strong>rEvolution Privacy Policy</strong> is subject to change
  at any time. CARET encourages you to review the privacy policy regularly for
  any changes. <br>
 <small><a href="#top">[Top]</a></small> <br>
 &nbsp;<br>