<h1>Acknowledgements</h1>

There have been many people involved in the creation of this site, and we would like to thank all of them.<br>
&nbsp;<br>
<b>For funding the project</b>: The Higher Education Funding Council for England (HEFCE).<br>
&nbsp;<br>
<b>For hosting the site</b>: Centre for Applied Research in Educational Technologies, University of Cambridge (CARET).<br>
&nbsp;<br>
<b>Partnership department</b>: Department of Zoology, University of Cambridge.

<h4>University Staff</h4>

The people from the many departments of the University of Cambridge who helped us with information, their time, support and knowledge:<br>
&nbsp;<br>
<b>Zoology Dept:</b> Michael Akam, Sarah Ferguson, Adrian Friday, Jenny Clack,  Ray Symmonds, Ann Charlton , Martin Ellwood, Matthew Wilkinson.<br>
<b>Plant Sciences Dept:</b> Ed Tanner, Beverley Glover, Howard Griffiths, Keith Johnstone.<br>
<b>Genetics Dept:</b> Mike Majerus.<br>
<b>Earth Sciences Dept:</b> Alan Smith, Sarah Finney and all the staff in the Sedgwick museum, especially Rod Long, Sally Daultrey and Annette Shelford.<br>
<b>Geography Dept:</b> Phil Gibbard, Steve Boreham.<br>
<b>Botanic Gardens:</b> Christine Preston, for providing photographs of plant specimens.<br>
<b>Homerton College:</b> Stephen Tomkins, Elaine Wilson, all the PGCE natural science students 2002-2003.<br>

<h4>Schools</h4>

The many teachers and students who have helped us design and test content for the site:<br>
&nbsp;<br>
Sandra Howard and the pupils of Charles Burrell School, Thetford.<br>
Marius, Mike Treby and the pupils of Bedminster Down Secondary School, Bristol.<br>
Maureen Alcorn and the pupils of St Martin-in-the-Fields School, London.<br>
Ronnie Thomas and the pupils of Archbishop Tenison's Church School, London.<br>
The pupils of Thurston Community College, Suffolk.<br>
Sally Kay and the pupils of Ely Community College.<br>
Jane Cooper and the pupils of Tonbridge Grammar School for Girls.<br>
The staff and pupils of Verulam school, St Albans.<br>
Staff at Sawston Village College.<br>

<h4>Others we would like to thank</h4>

We would especially like to thank Jem Rashbass, Kathryn Lawrence, Harriet Truscott, Sultan Kus, Tristan Last, Karen Wells and all the staff at CARET.<br>
Martyn Robertson was instrumental in researching computer game technology and research during the early stages of this site's development.<br>
Miranda Gomperts and Enrique Amaya for their support and for supplying photographs.<br>
All the people who agreed to be video interviewed for the site: Beverley Glover, Sean Crawford, Divya Mohan, Matt Curnock, Adam Powell, Sarah Finney, Matt Wilkinson, Adrian Friday, Rod Long and Ed Turner.<br>
David Livesey, Cambridge University Secretary-General of the Faculties, and Rosemary Butcher from the Admissions Office.