<h1>Fact Files</h1>

Below are extended versions of the text from the <a href="index.php?section=museum&template=hc&movie=beach" onclick="popUpMuseum(this.href); return false;">History of Life</a> time travel sequence. Each file covers a particular topic in the show.

<ul class="dinohand">


<li><a href="pdfs/factfiles/acanthostega.pdf">Acanthostega</a></li>
<li><a href="pdfs/factfiles/algae.pdf">Algae</a></li>
<li><a href="pdfs/factfiles/allosaurus.pdf">Allosaurus</a></li>
<li><a href="pdfs/factfiles/anomalocaris.pdf">Anomalocaris</a></li>
<li><a href="pdfs/factfiles/butterfly.pdf">Butterfly</a></li>
<li><a href="pdfs/factfiles/clubmoss.pdf">Clubmoss</a></li>
<li><a href="pdfs/factfiles/cockroach.pdf">Cockroach</a></li>
<li><a href="pdfs/factfiles/conifer.pdf">Conifer</a></li>
<li><a href="pdfs/factfiles/cooksonia.pdf">Cooksonia</a></li>
<li><a href="pdfs/factfiles/crinoid.pdf">Crinoid</a></li>
<li><a href="pdfs/factfiles/cycad.pdf">Cycad</a></li>
<li><a href="pdfs/factfiles/dipterocarp.pdf">Dipterocarpseed</a></li>
<li><a href="pdfs/factfiles/early.pdf">Early Spider</a></li>
<li><a href="pdfs/factfiles/echmatocrinus.pdf">Echmatocrinus</a></li>
<li><a href="pdfs/factfiles/eiffelia.pdf">Eiffelia</a></li>
<li><a href="pdfs/factfiles/ferns.pdf">Ferns</a></li>
<li><a href="pdfs/factfiles/fruitbats.pdf">Fruitbats</a></li>
<li><a href="pdfs/factfiles/geological.pdf">Geological Ages</a></li>
<li><a href="pdfs/factfiles/giant.pdf">Giant Dragonfly</a></li>
<li><a href="pdfs/factfiles/horsetails.pdf">Horsetails</a></li>
<li><a href="pdfs/factfiles/hummingbirds.pdf">Hummingbirds</a></li>
<li><a href="pdfs/factfiles/ichthyostega.pdf">Ichthyostega</a></li>
<li><a href="pdfs/factfiles/liverworts.pdf">Liverworts</a></li>
<li><a href="pdfs/factfiles/moths.pdf">Moths</a></li>
<li><a href="pdfs/factfiles/rafflesia.pdf">Rafflesia</a></li>
<li><a href="pdfs/factfiles/rhamphorynchus.pdf">Rhamphorynchus</a></li>
<li><a href="pdfs/factfiles/rhynia.pdf">Rhynia</a></li>
<li><a href="pdfs/factfiles/scutellosaurus.pdf">Scutellosaurus</a></li>
<li><a href="pdfs/factfiles/snake.pdf">Snake</a></li>
<li><a href="pdfs/factfiles/sponges.pdf">Sponges</a></li>
<li><a href="pdfs/factfiles/tarsier.pdf">Tarsier</a></li>
<li><a href="pdfs/factfiles/tree.pdf">Treefern</a></li>
<li><a href="pdfs/factfiles/trilobite.pdf">Trilobite</a></li>
<li><a href="pdfs/factfiles/vauxia.pdf">Vauxia</a><br></li>

</ul>

These files are in Adobe Acrobat (PDF) format. If you do not have Adobe Acrobat then then <a href="http://www.adobe.com/products/acrobat/readstep2.html">download the reader here</a>.