<div align="left">
<h2>Help with using computers in the classroom</h2>
<br>
If you are unfamiliar with the use of computers in the classroom, or have specific
questions about technology, you can find advice tailored to your needs at these
sites:
<br>
<br>
<a href="http://www.curriculumonline.gov.uk/Curriculum+OnLine/TeacherInfo/newtothenet.htm" target="_blank">New to the Net</a>, an advice page for teachers and others who may be using the Internet for the first time. Developed by Curriculum Online.
 <br>
<a href="http://www.curriculumonline.gov.uk/Curriculum+OnLine/TeacherInfo/usingdigitalresources.htm " target="_blank">Using digital resources</a> - advice for teachers on how to incorporate digital resources (including rEvolution!) into class work.
  <br>
  <br>
<a href="http://www.ictadvice.org.uk/" target="_blank">ICT advice</a> - advice for teaching staff from Becta (British Educational Communications and Technology Agency) on the uses of Information technologies.
  <br>
  <br>
<a href="http://www.schoolzone.co.uk/" target="_blank">Schoolzone</a> are the largest provider of educational software in the UK. Originally established in 1997 by a group of enthusiastic teachers and parents from the Oxford area, they now review and list suitable Internet sites, software and other resources for use in schools at any age.
<br>
<br>
<a href="http://www.icteachers.co.uk/index.htm" target="_blank">ICT Teachers</a> - another site written by teachers for
  teachers. This site contains and indexes many resources that can be used in
  the classroom, as well as having many lesson plans to download. Developed by
  Becta.
  <br>
<br>
<a href="http://illumina.3tproducts.co.uk/naace_attachments/14_6828d9e9.doc" target="_blank">Illumina document</a> - a fascinating
  document outlining many reasons for using information technology (computers)
  in the classroom and giving good examples of how the use of ICT can enhance
  the learning process for students.
  <br>
<br>
<a href="http://www.teachernet.gov.uk/ " target="_blank">Teachernet</a> - run by the Department of Education and Skills,
  this is a web site developed for use by parents and teachers alike, and contains
  many useful resources.
  <br>
<br>
<a href="http://www.curriculumonline.gov.uk/Curriculum+OnLine/cover.htm" target="_blank">Curriculum Online</a> - the entire
  Curriculum Online, a great way to check up on anything new, browse lesson plans
  or contact your peers for help.
  <br>
<br>
</div>
