<h1>Help</h1>

If you're lost, then try looking at the <a href="index.php?section=sitemap">Site Map</a>.

<br>&nbsp;<br>

If you are having difficulty viewing this site, it may be because you do not have the right software installed. Below are details of the software required:

<h3>Flash</h3>
  The majority of this site has been constructed using Macromedia Flash&reg;
  If you do not have Flash&reg; installed on your computer, you
  can download a free version of the program here
  <br>
<a href="http://www.macromedia.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" target="_blank">Shockwave download</a>
<br>

<h3>JavaScript</h3>
  To access the Museum and video sections of the site you must have JavaScript turned on. To turn on JavaScript in Internet Explorer, select 'Internet Options' on the 'Tools' menu. Then click on the 'Security' tab, and then the 'Custom Level...' button. Then set the 'Active Scripting' option on the list (down near the bottom) to 'Enabled'.
<br>
  <h3>PDF files</h3>
   Some of the documents on this site are available for you to download and print.
  These documents are in Adobe Acrobat&reg; format, and in order to read
  them, you will need to have Adobe Acrobat Reader&reg; installed on your computer.
  You can download the reader for free at:
 <br>
<a href="http://www.adobe.com/products/acrobat/readstep2.html" target="_blank">Adobe acrobat download</a>
<br>
<h3>Windows Media Player 9</h3>
  You will need Windows Media Player 9 &reg; to play the audio and video files for Virtual Museum tours and Sound Bite interviews.
  You can get a free download of the software here:
<br>
<a href="http://www.microsoft.com/windows/windowsmedia/9series/player.aspx" target="_blank">
Windows mediaplayer 9 download</a>
<br>
<h3>Other problems</h3>

If you think there is a different problem with the site, then please <a href="index.php?section=contact">contact us</a> and tell us about it.