Welcome to the <b>rEvolution</b> homepage! <b>rEvolution</b> is the online biology experience from Cambridge University. To get started, click on one of the graphics below!<br>
&nbsp;

<center>

<table cellpadding="0" cellspacing="0" width="75%">
<tr>

<td width="50%" align="center" valign="middle">
<p>
  <a href="index.php?section=museum&template=hc" onclick="popUpMuseum(this.href); return false;">
  <img src="images/layout/museumicon.gif" alt="Interactive museum" border="0"></a>
</p>

</td>

<td width="50%" align="center" valign="middle">

<p>
  <a href="index.php?section=museum&template=hc&movie=careers" onclick="popUpMuseum(this.href); return false;">
  <img src="images/layout/informationicon.gif" alt="Information Centre" border="0"></a>
</p>

<!--
  <OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" WIDTH="280" HEIGHT="250" id="froggy" ALIGN=""> <PARAM NAME=movie VALUE="flash/froggy.swf"> <PARAM NAME=menu VALUE=false> <PARAM NAME=quality VALUE=high> <PARAM NAME=wmode VALUE=transparent> <PARAM NAME=bgcolor VALUE=#006666> <EMBED src="flash/froggy.swf" menu=false quality=high wmode=transparent bgcolor=#006666  WIDTH="280" HEIGHT="250" NAME="froggy" ALIGN="" TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer"></EMBED>
  </OBJECT> -->

</td>
</tr>
</table>

</center>