<h2>The Information Centre</h2>

<p>The <a href="index.php?section=museum&template=hc&movie=careers" onclick="popUpMuseum(this.href); return false;">information centre</a> contains:</p>

<ul class="dinohand">

<li><a href="index.php?section=teachers">Staff room</a> - a collection of documents for teachers (and parents) providing guides for using the site, the games, activities and the information on rEvolution, as well as building over time into a comprehensive resource about the use of ICT in classroom teaching.</li>

<li><a href="index.php?section=careers">Careers centre</a> - an area providing career advice to students and their families about the choices they face, the opportunities open to them and how to navigate their way through the hurdles of University admission.</li>

<li><a href="index.php?section=resources">Resources</a> - a whole host of fun and entertainment for students, parents and staff. Want to know when International Bat Week is on? Need to find somewhere to take the kids in Devon in December? Want to know how to go out and collect beetles? All of this - and more - can be found hidden behind the bookcase.</li>

<li><a href="index.php?section=scientists">Famous scientists</a> - the science you study at school was once a mystery, slowly discovered, thought about and painstakingly investigated by men and women who had none of the advantages of television, international magazines and conferences or websites to help them. Yet a handful of people managed to investigate, explore and theorise their way through the mystery and build the basis on which every scientist today depends.</li>

<li><a href="index.php?section=vids_careers">Sound bites</a> - these videos are part of the careers information provided on the site - but are not the normal boring waffle that you might expect. We have tracked down people doing interesting jobs across the field in natural sciences, as well as woken up a few students to tell us what their student life is really like. If you like science, but don't know what you might do with a biology degree, sit and listen to these videos and let our experts inspire you!</li>

<li><a href="index.php?section=vids_careers#museums">Museum tours</a> - these virtual museum tours are videos of museum staff taking you on a magical mystery tour of their favourite exhibits in two of the world's oldest and most famous museums. By turns, these videos are funny, frank and absolutely fascinating, and ensure that you'll never see museums as boring again! So why not take a tour from the comfort of your armchair?</li>

</ul>