<h1>Weblinks</h1>

During our research for this site, we came across so many interesting, funny, scary and surprising websites that we just had to share some of our favourites with you. If you know of a site that ought to be added to the list, then drop us an email or use the feedback form and let us know!

<h3>General</h3>

<a href="http://www.bbc.co.uk/nature/">BBC Nature</a><br>

<a href="http://www.bbc.co.uk/gardening/htbg2/virtual_garden/">The virtual garden</a><br>

<a href="http://www.thenakedscientists.com/">The Naked Scientists online</a><br>

<a href="http://www.zoo.cam.ac.uk/ioz/">The Institute of Zoology</a><br>

<a href="http://insideout.rigb.org/insideout/">The Royal Institution of Great Britain</a> - The people who run the Christmas lectures.<br>

<h3>Younger audience</h3>

<a href="http://www.bbc.co.uk/cbbc/wild/games/">CBBC Nature</a> - Site for young people.<br>

<a href="http://www.kidsplanet.org/">Kids planet</a> - Wildlife facts and games.<br>

<h3>Conservation of wildlife</h3>

<a href="http://www.arkive.org/">Arkive biodiversity project</a><br>

<a href="http://www.english-nature.org.uk/">English Nature</a><br>

<a href="http://www.wwf.org/">World Wildlife Fund</a><br>

<a href="http://www.zoo.cam.ac.uk/ccf/">Cambridge Conservation Forum</a><br>

<a href="http://www.cee.org.uk">Council for Environmental Conservation</a><br>

<a href="http://www.ukbap.org.uk/ebg/">England Biodiversity Group</a><br>

<a href="http://www.woodland-trust.org.uk/">The Woodland Trust</a><br>

<h3>Science/nature centres and museums</h3>

<a href="http://www.at-bristol.org.uk/Default.htm">Bristol’s science district</a> - Ready for you to explore.<br>

<a href="http://www.at-bristol.org.uk/wildwalk/default.htm">WildWalk</a> - A host of mini-creatures to visit.<br>

<a href="http://www.nhm.ac.uk/">Natural History Museum, London</a><br>

<a href="http://www.dynamicearth.co.uk/first_time_visitors.asp">Dynamic Earth centre, Edinburgh</a><br>

<a href="http://www.botanic.cam.ac.uk/">Cambridge University Botanic Gardens</a><br>

<a href="http://www.24hourmuseum.org.uk/">The 24 hour museum</a> – the UK’s museums, open at all hours!<br>

<a href="http://www.ecsite-uk.net/index.php">ECSITE-UK</a> - A list of all of the nature and science centres in the UK for you to visit!<br>

<a href="http://www.giveusahome.co.uk/daysout.htm">Days Out</a> - A great list of places to go to visit animals (not just zoos!)<br>

<h3>Science subjects</h3>

<a href="http://www.dnaftb.org/dnaftb/">DNA from the beginning</a><br>

<a href="http://www.dnalc.org/">The Dolan DNA learning centre</a><br>

<a href="http://www.ucalgary.ca/UofC/eduweb/virtualembryo/">The virtual embryo (developmental biology)</a><br>

<h3>Biology sites for educators</h3>


<a href="http://www.schoolscience.co.uk/content/index.asp">SchoolScience</a><br>

<a href="http://www.biology.arizona.edu/">The Biology Project</a><br>

<a href="http://waynesword.palomar.edu/wayne.htm">Wayne’s Word</a> - A huge on-line natural history encyclopaedia.<br>

<a href="http://www-saps.plantsci.cam.ac.uk/">Science and Plants for Schools</a><br>

<a href="http://www.ase.org.uk/">The Association for Science Education, UK</a><br>

<a href="http://www.scienceyear.com/home.html">Planet Science</a> - An initiative from the Department of Education for excellence in science teaching.<br>

<a href="http://www.ncbe.reading.ac.uk/">The National Centre for Biotechnical Education</a> - Based at the University of Reading. Masses of information about genes, biotechnology and genetic modification – as well as a comprehensive array of classroom kits to buy and experiment with.<br>

<h3>Suppliers</h3>

<a href="http://www.besanet.org.uk/index.htm">The British Educational Suppliers Association</a>
 - BESA provides an introduction to over 250 suppliers of scientific and educational equipment and resources. With new products being released all the time, it pays to keep an eye out here!<br>

<a href="http://www.blades-bio.co.uk/">Blade’s Biological suppliers</a>
- Blade's provide a variety of live and preserved invertebrates and plants, as well as much of the equipment needed to collect then in the field and keep them in the classroom.<br>

<a href="http://www.philipharris.co.uk/">The Philip Harris Company</a> - Philip Harris is one of the largest suppliers of teaching equipment in the UK. They have an extensive catalogue of kits, equipment, invertebrates and plants and other resources to help you teach science in the field and the classroom.<br>

<a href="http://www.watdon.com/watdon_home.html">Watkins and Doncaster</a> -
Watkins and Doncaster have been supplying field collecting and storage equipment for over 130 years. Get all of your butterfly nets, pooters, mounting pins and museum display boxes here!<br>


<h3>Other links:</h3>

<a href="http://puzzling.caret.cam.ac.uk/ageselect.php">Brainteasers and Puzzles project</a><br>

<a href="http://www.mmp.maths.org.uk/index.html">Millennium Maths Project</a><br>

<a href="http://www.seekscience.org">SEEK, Science and Engineering Experiments for Kids</a><br>