<h1>You Don't Have Flash!</h1>

We have detected that your web browser does not have the Flash 6 Player installed. You will need the Player to visit the museum. It only takes a few minutes to download - please click on the icon below.

<br />&nbsp;<br />

</div>

<div align="center"><a href="http://www.macromedia.com/shockwave/download/alternates/#win" target="_blank">

<img src="images/layout/get_flashplayer_88_31.gif" alt="Get Flash icon" width="88" height="31" border="0"></a>

<br />&nbsp;<br />

</div>

<div>

If you are on a network, you will need to be first logged in as an administrator to install the new player. If you have any problems then ask whoever is in charge of the computer to help.

<br />&nbsp;<br />

Once you have installed the Flash Player, you can <a href="index.php?section=museum&templat=hc">Visit the Museum</a>.