<div align="left">

<h1>Resources</h1>

<ul class="dinohand">

<li>
	<a href="index.php?section=sitenews">rEvolution News</a><br>
	The latest news about the rEvolution site.</li>

<li>
	<a href="index.php?section=sciencenews">Science News</a><br>
	All the latest science news from the New Scientist<!-- and the BBC -->.</li>

<li>
	<a href="index.php?section=links">Links</a><br>
	Websites that we have found that are cool, interesting and useful.</li>

<li>
	<a href="index.php?section=books">Bookshelf</a><br>
	Not everything about science is on this site! Here are some great books to read as well.</li>

<li>
	<a href="index.php?section=articles">Articles</a><br>
	Suggestions for getting out of the classroom and getting to grips with some wild biology.</li>

<li>
	<a href="index.php?section=calendar">Calendar</a><br>
	A calendar of cool science-related events throughout the year.</li>

<li>
	<a href="index.php?section=factfiles">Fact Files</a><br>
	In-depth info on the species featured in the <i>History of Life</i>.</li>


<li>
	<a href="index.php?section=glossary">Glossary</a><br>
	Don't know what a particular word is? Check out our searchable glossary of words.</li>

<li>
	<a href="index.php?section=contact">Feedback</a><br>
	Dying to tell us what you think of the site? Send us your messages here.</li>


</ul>

</div>