<div align="left">
<h2>Famous Scientists </h2>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="130"><img src="images/photos/darwinsmall.jpg" alt="Charles Darwin" width="102" height="135" border = "0"></td>
    <td width="1044"> <p>Charles Darwin<br>
        <u>(1809 -1882)</u></p>
          <p>Find out more about the shy man who collected finches and shells in the
          Galapogos Islands, wrote a book all about earthworms at the age of 72,
          and incidentally kicked off one of the biggest rows in Victorian society
          with a simple booklet.<br>
          <a href="index.php?section=darwin">Find out more...</a></p>
        <p></p></td>
  </tr>
  <tr>
    <td><img src="images/photos/sedgwicksmall.jpg" alt="Adam Sedgwick" width="102" height="134" border = "0"></td>
    <td><p>Adam Sedgwick<br>
        <u>(1785 -1823)</u></p>
     <p>Discover one of the most prolific fossil and rock hunters of his time
          - a man who taught Darwin geology, was laughed at for lecturing
          to women and still taught undergraduates at the age of 86.<br>
        <a href="index.php?section=adamsedgwick">Find out more...</a></p>
      </td>
  </tr>
</table>
</div>
