<h1>rEvolution News</h1>


<b>'Reaction'</b><br>
Friday 12th – Saturday 20th March<br>
The University of Cambridge’s annual Science Festival<br>
-Free hands-on demonstrations and fun-based activities for all ages in many departments across the university<br>
-Meet ‘top’ scientists to discuss latest scientific discoveries<br>
-Preview rEvolution’s genetics section at the Wellcome/CRUK Gurdon Institute on Saturday 13th march between 2 and 5pm.<br>
<br>
For more information about the events running during the science festival please call 01223 766766

<br>
<b>The rEvolution gets underway!</b><br>
Today (16th October 2003) the brand spanking new rEvolution website was launched <br>
<a href="http://www.caret.cam.ac.uk/news/news_stories_oct03.htm#revolution">Read More...</a><br>

<br>
<b>The rEvolution team visit some very old friends at the Sedgwick museum...</b><br>
<a href="http://www.caret.cam.ac.uk/news/news_stories_jan03.htm#fossils">Read More...</a>
<!-- http://www.caret.cam.ac.uk/news/photos_fossils.htm  -->
