<h1>Site Map</h1>

<div>

<h4>Main Pages</h4>

<ul class="dinohand">

<li><a href="index.php">Home Page</a></li>
<li><a href="index.php?section=museum&template=hc" onClick="popUpMuseum(this.href); return false;">rEvolution Museum</a></li>
<li><a href="forum/">rEvolution Forums</a></li>

</ul>

<h4>Information</h4>

<ul class="dinohand">

<li><a href="index.php?section=museum&template=hc&movie=careers" onClick="popUpMuseum(this.href); return false;">Information Centre</a></li>
<li><a href="index.php?section=teachers">Staff Room</a></li>

</ul>

<h4>Careers</h4>

<ul class="dinohand">

<li><a href="index.php?section=careers">Careers Centre</a></li>
<li><a href="index.php?section=vids_careers">Sound Bites</a></li>
<li><a href="index.php?section=studentstuff">Student Stuff</a></li>
<li><a href="index.php?section=universityinfo">Cambridge University information</a></li>

</ul>

<h4>Resources</h4>

<ul class="dinohand">

<li><a href="index.php?section=resources">Resource Index</a></li>
<li><a href="index.php?section=sciencenews">Science In The News</a></li>
<li><a href="index.php?section=links">Science Links</a></li>
<li><a href="index.php?section=scientists">Famous Scientists</a></li>
<li><a href="index.php?section=glossary">Glossary</a></li>

</ul>

<h4>Help</h4>

<ul class="dinohand">

<li><a href="index.php?section=help">Help with this site and technology</a></li>
<li><a href="index.php?section=helpclassroom">Help with using technology in the classroom</a></li>

</ul>

<h4>Site information</h4>

<ul class="dinohand">

<li><a href="index.php?section=about">About rEvolution</a></li>
<li><a href="index.php?section=contact">Contact Page</a></li>
<li><a href="index.php?section=credits">Acknowledgements</a></li>
<li><a href="index.php?section=copyright">Copyright Notice &amp; Disclaimer</a></li>

</ul>

</div>