<div align="left">

<h1>Students' Stuff</h1>
<br>Are you looking for a way to finance your way through University? Do you want 
  to know what it is really like to be a student for the first time? How do people 
  manage to find time to study when there are so many other interesting things 
  going on?<br>
<br>The answer may be in here. We have gathered together some links to get you 
  started on the road to being a student - and some more to keep you going!<br>
  
  
<h2>Funding</h2>
<a href="http://www.dfes.gov.uk/index.htm" target="_blank">The Department for Education and Skills</a> 
  This is the Government department responsible for education in the UK, including 
  University education. They have some useful information about the different 
  types of fee you will have to pay to study at university, as well as advice 
  on where to look for funding. 
  <br>
  
  
<h2>Alternative prospectuses</h2>
<a href="http://www.realuni.com/" target="_blank">Alternative student handbooks</a> are written by students
  themselves, and often give a very different view of life at University! This 
  site contains possibly the most comprehensive alternative student guide ever, 
  with answers to many of the issues that face students.
  <br>
  <br>
  <a href="http://www.cusu.cam.ac.uk/publications/altpro/" target="_blank"> the Alternative prospectus 
  for Cambridge University</a>, with details of the many clubs and societies to join 
  as well as the best places to eat, hang out and have a good time in the city.
  <br>
  
<h2>University applications</h2>
  <a href="http://www.ucas.ac.uk/" target="_blank">UCAS (University & Colleges Admissions Service)</a> 
  This site is the official home of UCAS, and has a huge amount of information 
  about the process of finding a course, university and funding if you decide 
  to go on to university. There is also lots of advice about some of the pressures 
  and problems you and your family may face during this time.
  <br>
<a href="http://www.ucas.ac.uk/getting/index.html" target="_blank">UCAS - Getting to University</a> A comprehensive collection of things 
  to think about before applying to university.
  <br>
  <br>
  
<h2>Open Days</h2>
  <a href="http://www.opendays.com/home.asp?loc=001" target="_blank">Find an Open Day</a> 
  Before you apply to a University, it is often a good idea to attend one of their Open Days and get a feel for 
  the accommodation, people, staff and the department you may be a member of. 
  This is the best website guide to when Universities across the country hold 
  their Open Days - so go and check 'em out.
  <br>
  <br>
  
<h2>Being a student</h2>
 <a href="http://www.realuni.com/" target="_blank"> The National Union of Students Unions</a> 
 This is the umbrella organisation to which all Students' Unions belong. In here 
  you will find lots of advice about all aspects of becoming or being a student 
  (including funding advice, what course to choose, how to cope with the first 
  few weeks..) and a variety of campaigns currently being carried out to make 
  student life easier.
  <br>
  <br>
  
<h2>Got something to say?</h2>
  If there is something you haven't found in here that you think is missing, 
  or if you have a suggestion for another link, then why not get in touch using our <a href="http://revolution.caret.cam.ac.uk/index.php?section=contact">contacts page</a> with your comments?
 <br>