<div align="left">
<h2>Staff Room</h2>

<p>
This section of the rEvolution site is here primarily for teaching staff who would like to use this resource in the classroom. And parents - why don't you take a look too?
</p>
<p>In here, you will find:</p>

<ul class="dinohand">

<li><a href="pdfs/historylifehandbook.pdf">Handbooks for the 'History Of Life' games and other activities</a> [PDF] These handbooks contain details of the main features of every game as well as a brief explanation of how to play. We suggest ways that the game could be used in the classroom or at home, and how it can lead on to other activities, as well as how the activities link into the National Curriculum.</li>

<li><a href="forum/index.php?board=6">Teacher-only discussion board</a> so that you can share information, concerns and gossip with each other</li>

<li>Guides to the <a href="index.php?section=infocentreguide">Information Centre</a> and <a href="index.php?section=careersguide">Careers Centre</a>, giving you an outline of the information and activities you will find on the site in each area</li>

<li><a href="index.php?section=help">Help with the technology</a> used on this site and where to download appropriate software</li>

<li><a href="index.php?section=helpclassroom">Help with using technology in the classroom</a>, and links to some organisations to inspire you further</li>

<li><a href="pdfs/bectaadvice.pdf">BECTA advice on teaching with ICT</a> [PDF] Expert advice on using ICT in the classroom.</li>

</ul>

</div>
