
<div align="left">

<h1>Cambridge University information</h1>
Although this site is largely about the wonders of our natural world - 
  and encouraging as many people as possible to go out and enjoy them - 
  we also have another mission. There are many bright, capable children out there 
  who do not consider going to University to study science subjects for a number 
  of reasons. We want to encourage you to think about how University could help 
  you to find a job, how you could spend another three years learning about your 
  favourite subject, how studying will bring new discoveries every day -
  go on, it's worth thinking about!
  <br>
  <br>
  rEvolution was initiated by the University of Cambridge, and so many of the 
  links below refer to Cambridge. We have had a lot of help from people working 
  in the departments of the University, and everyone we have spoken to is very 
  keen to attract people into studying the "Natural Sciences". This 
  includes Biology, Botany, Zoology, Geology (sometimes called Earth Sciences) 
  and Biotechnology.
  <br>
  <br>
Here are a few links to help you find out information about the University 
  before you apply, as well as where to go to find help and support once you are 
  there.
  <br>
   <br>
<br>
<h2>The University</h2>
<a href="http://www.cam.ac.uk/" target="_blank">Cambridge University homepage</a>
<br>
<br>

<a href="http://www.cam.ac.uk/cambuniv/courses.html" target="_blank">Course Information</a> - The University lists all of the 
  courses open to undergraduates here. This page also links through to the Admissions 
  Department.
  <br>
  <br>
  
<a href="http://www.cam.ac.uk/cambuniv/ugprospectus/" target="_blank">Undergraduate Prospectus</a> - This is the official online Undergraduate 
  prospectus, written in collaboration with the Student Union to help you discover 
  what it is like to study at Cambridge, and how to get there.
  <br>
  <br>
  
<a href="http://www.cam.ac.uk/cambuniv/ugprospectus/welcome/welcome12.html" target="_blank">Come to an Open Day</a> - Want to 
  drop in and find out what the colleges are like? Fancy a day in Cambridge to 
  absorb the atmosphere before applying? Then why not come along to an Open Day 
  at the colleges and departments, where you can meet staff and students and find 
  out if Cambridge would suit you. This page lists the Open Days for 2003, but 
  is updated regularly.
  <br>
  <br>
<a href="http://www.cam.ac.uk/cambuniv/termdates.html" target="_blank">Cambridge University term dates</a> - There is nothing like planning 
  ahead... so here are the term dates for Cambridge University from 2003 to 
  2020!
   <br>
   <br>
<br>
<h2>Studying Natural Sciences @ Cambridge University</h2>
<a href="http://www.justanotherstudio.co.uk/ac/" target="_blank">Cambridge University application process</a> - How to apply to Cambridge University. 
This page has been set up by the Student Union to help prospective students, answer 
their questions and tell it like it really is....
<br>
<br>

Below, you will be able to discover the full range of scientific opportunities 
  available at Cambridge, as well as what fascinating research each department 
  is currently working on.
  <br>
 <br>
 
<a href="http://www.bio.cam.ac.uk/sbs/facbiol/" target="_blank">Faculty of Biology</a> This is the umbrella 
  department that all of the natural science departments belong to, and gives 
  a good overview of all related activities and departments at Cambridge.
  <br>
  <br>
  <a href="http://www.bio.cam.ac.uk/" target="_blank">School of Biological Sciences</a>
  <br>
  <br>
<a href="http://www.zoo.cam.ac.uk/" target="_blank">Department of Zoology</a>
<br>
<br>
<a href="http://www.bioc.cam.ac.uk/" target="_blank">Department of Biochemistry</a>
<br>
<br>

<a href="http://www.plantsci.cam.ac.uk/ " target="_blank">Department of Plant Sciences</a>
<br>
<br>
<a href="http://www.esc.cam.ac.uk/" target="_blank">Department of Earth Sciences</a>
<br>
<br>
<a href="http://www.gen.cam.ac.uk/" target="_blank">Department of Genetics</a>
<br>
<br>
<a href="http://www.phy.cam.ac.uk/" target="_blank">Department of Physics</a>
<br>
<br>
<a href="http://www.ch.cam.ac.uk/" target="_blank">Department of Chemistry</a>
  <br>
   <br>
<br>
<h2>Places to go for help (once you're at Cambridge)</h2>
<a href="http://www.admin.cam.ac.uk/offices/accommodation/intro.html" target="_blank">The University Accommodation 
service</a> helps students to find a place to stay if they decide to move out of their 
College. However, the vast majority of students at Cambridge will be accommodated 
within their College at least for the first year. 
<br>
<br>

<a href="http://www.admin.cam.ac.uk/about-off.html" target="_blank">The University Administration office</a> 
  contains the people who have the huge task of actually ensuring the smooth running 
  of the University. It is always a good place to start looking for help and advice; 
  if the department can't help you, they will surely know who can.
  <br>
  <br>
  
<a href="http://www.careers.cam.ac.uk/" target="_blank">The excellent Careers Service</a>  is one of the 
  reasons that 98% of Cambridge graduates are employed within a year of leaving 
  the University. The staff run a truly amazing number of events, talks, careers 
  fairs and face-to-face interviews over the year, as well as providing a comprehensive 
  library of careers resources.
  <br>
  <br>
  
<a href="http://www.cam.ac.uk/cs/ " target="_blank">The Computing Service </a> oversees computing facilities 
  throughout the University and provides a range of services from training to 
  accounts for students. The first place to go if you have any technical problems.
 <br>
 <br>
 
<a href="http://www.cam.ac.uk/cambuniv/disability/" target="_blank">The Disability Resource Centre</a> provides facilities and support for any student with difficulties, including 
  limited places in purpose-built accommodation units.
  <br>
  <br>
  
<a href="http://www.sport.cam.ac.uk/" target="_blank">The Sports department</a> - The University has a huge range of sports and 
  leisure facilities, and each of the Colleges has their own facilities as well. 
  There are many clubs to join from the traditional rowing to the unusual Ultimate 
  Frisbee, so there is no excuse for not getting involved!
  <br>
  <br>
  
<a href="http://www.lib.cam.ac.uk/" target="_blank">The University Library</a>  is one of the largest University 
  libraries in the country, as well as being a copyright library. New technology 
  allows you to search through books held in departments and colleges too to find 
  that elusive book.
  <br>
  <br>
  
<a href="http://www.cam.ac.uk/cambuniv/linkline/" target="_blank">LinkLine</a> is a voluntary counselling 
  service run by students for students and open 24 hours a day to provide help, 
  advice and support to students in trouble.
  <br>
  <br>
  
<a href="http://www.cusu.cam.ac.uk/" target="_blank">Cambridge University Student's Union</a>  Not 
  just a social centre, but a whirlwind of campaigning on students' behalf, 
  home of the University's many clubs and societies and somewhere to find 
  good food cheap!
  <br>

</div>