<div align="left">

<h1>Sound Bites</h1>
Give your eyes a rest from reading and instead sit back and listen to some
 scientists talking about what they do, how they got into science and what it
 is that they love so much about it.<br>
 <br>
 Our volunteers include:  <br>&nbsp;<br>

<ul class="dinohand">

	<li>
	<a href="video/select_bw.php?video=careers/beverley" onclick="arkadev4_DoFSCommand('openwindow','careers/beverley'); return false;">Dr Beverley Glover</a>
	<br>
	Project leader for the molecular development group in the
	Plant Sciences Dept, Cambridge University<br>
	</li>


	<li>
	<a href="video/select_bw.php?video=careers/sarah" onclick="arkadev4_DoFSCommand('openwindow','careers/sarah'); return false;">Dr Sarah Finney</a>
	<br>
	Geological Conservator for the Sedgwick Museum of Geology, Cambridge<br>
	</li>



	<li>
	<a href="video/select_bw.php?video=careers/sean" onclick="arkadev4_DoFSCommand('openwindow','careers/sean'); return false;">Sean</a>
	<br>
	Conservation officer for DEFRA (Department for Environment, Food and Rural Affairs)<br>
	</li>




	<li>
	<a href="video/select_bw.php?video=careers/adam" onclick="arkadev4_DoFSCommand('openwindow','careers/adam'); return false;">Adam Powell</a>
	<br>
	Student teacher in natural sciences<br>
	</li>

	<li>
	<a href="video/select_bw.php?video=careers/divya" onclick="arkadev4_DoFSCommand('openwindow','careers/divya'); return false;">Divya Mohan</a>
	<br>
	Medical student at Cambridge University<br>
	</li>

	<li>
	<a href="video/select_bw.php?video=careers/matt" onclick="arkadev4_DoFSCommand('openwindow','careers/matt'); return false;">Matt Curnock</a>
	<br>
	Researcher for an Eco-tourist operator<br>
	</li>

	<li>Matt Wilkinson
	<br>
	Research scientist on pterosaur flight<br>
	</li>

</ul>

<a name="museums"></a><h2>Virtual Museum Tours!</h2>

We also have begun a series of guided virtual tours of famous museums, conducted by the staff of those museums. In these tours, the staff member will take you around the museum to see some of their favourite exhibits, and give you a personal insight into an amazing museum.

 <br>&nbsp;<br>

<ul class="dinohand">

	 <li><a href="index.php?section=vids_sedgwick", "_blank">Rod Long</a>
  <br>
	Sedgwick museum of Geology, Cambridge University<br>
 </li>

	 <li><a href="index.php?section=vids_zoology", "_blank">Adrian Friday</a>
  <br>
	Zoology museum, Cambridge University</li>

</ul>

	</div>
