 <h2>Sedgwick Museum Videos</h2>

<img src="images/maps/sedgwick_museum_map.gif" alt="Map of the Sedgwick" width="700" height="550" border="0" usemap="#Map">
<map name="Map">
  <area shape="poly" coords="75,185,145,185,145,143,186,143,186,176,171,176,171,205,75,205" href="video/select_bw.php?video=sedgwick/hippo" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/hippo'); return false;" alt="Hippopotamus">

  <area shape="poly" coords="188,143,225,143,225,185,285,185,285,206,201,206,201,175,188,175" href="video/select_bw.php?video=sedgwick/elephant" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/elephant'); return false;"	alt="Deinotherum">

  <area shape="poly" coords="168,22,271,22,271,46,226,46,242,110,270,110,270,134,222,134,222,110,233,110,214,45,168,45" href="video/select_bw.php?video=sedgwick/salamander" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/salamander'); return false;" alt="Cryptobranchus">

  <area shape="poly" coords="307,21,380,21,380,46,343,46,331,110,351,110,351,134,304,134,304,110,319,110,332,45,307,45" href="video/select_bw.php?video=sedgwick/iguanodon" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/iguanodon'); return false;" alt="Iguanodon">

  <area shape="poly" coords="483,102,512,94,517,113,578,113,578,135,522,135,527,152,497,160" href="video/select_bw.php?video=sedgwick/pleisiosaurus" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/pleisiosaurus'); return false;" alt="Pleisiosaur">

  <area shape="poly" coords="508,237,550,225,554,243,667,243,667,259,559,259,560,264,518,276" href="video/select_bw.php?video=sedgwick/carboniferous" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/carboniferous'); return false;" alt="Carboniferous">

  <area shape="poly" coords="541,355,580,344,583,360,652,360,652,381,588,381,550,392" href="video/select_bw.php?video=sedgwick/burgess" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/burgess'); return false;" alt="Burgess Shale">

  <area shape="poly" coords="552,393,591,383,595,397,653,397,653,414,597,414,599,419,562,431" href="video/select_bw.php?video=sedgwick/intro" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/intro'); return false;" alt="Introduction">

  <area shape="poly" coords="503,446,598,421,610,459,513,485" href="video/select_bw.php?video=sedgwick/adamsedgwick" onclick="arkadev4_DoFSCommand('openwindow','sedgwick/adamsedgwick'); return false;" alt="Adam Sedgwick">
</map>
