<h2>Zoology Museum Videos</h2>
<h3>Upstairs</h3>
<p><img src="images/maps/zoology_museum_downstairs.gif" alt="Downstairs Map" border="0" usemap="#Map">
</p>
<h3>Downstairs</h3>
<p><img src="images/maps/zoology_museum_upstairs.gif" alt="Upstairs Map" width="700" height="550" border="0" usemap="#Map2">
  <map name="Map2">
    <area shape="rect" coords="17,475,505,541" href="video/select_bw.php?video=museum/whale" onclick="arkadev4_DoFSCommand('openwindow','museum/whale'); return false;" alt="Whale">
  </map>
  <map name="Map">
    <area shape="rect" coords="399,510,496,535" href="video/select_bw.php?video=museum/monotremes" onclick="arkadev4_DoFSCommand('openwindow','museum/monotremes'); return false;" alt="Monotremes">

    <area shape="rect" coords="307,510,399,535" href="video/select_bw.php?video=museum/marsupials" onclick="arkadev4_DoFSCommand('openwindow','museum/marsupials'); return false;" alt="Marsupials">

    <area shape="rect" coords="213,510,305,535" href="video/select_bw.php?video=museum/insectivores" onclick="arkadev4_DoFSCommand('openwindow','museum/insectivores'); return false;" alt="Insectivores">

    <area shape="rect" coords="153,510,209,535" href="video/select_bw.php?video=museum/bats" onclick="arkadev4_DoFSCommand('openwindow','museum/bats'); return false;" alt="Bats">

    <area shape="rect" coords="64,509,149,535" href="video/select_bw.php?video=museum/primates" onclick="arkadev4_DoFSCommand('openwindow','museum/primates'); return false;" alt="Primates">

    <area shape="rect" coords="16,426,46,541" href="video/select_bw.php?video=museum/greatapes" onclick="arkadev4_DoFSCommand('openwindow','museum/greatapes'); return false;" alt="Great Apes">

    <area shape="poly" coords="16,101,104,101,104,127,143,156,143,306,311,306,344,435,58,435,58,330,16,330" href="video/select_bw.php?video=museum/ungulates" onclick="arkadev4_DoFSCommand('openwindow','museum/ungulates'); return false;" alt="Ungulates">

    <area shape="poly" coords="91,52,313,52,313,132,116,132,107,125,107,100,91,83" href="video/select_bw.php?video=museum/carnivores" onclick="arkadev4_DoFSCommand('openwindow','museum/carnivores'); return false;" alt="Carnivores">

    <area shape="rect" coords="17,38,69,85" href="video/select_bw.php?video=museum/aardvark" onclick="arkadev4_DoFSCommand('openwindow','museum/aardvark'); return false;" alt="Aardvark">

    <area shape="rect" coords="436,95,480,153" href="video/select_bw.php?video=museum/sloth" onclick="arkadev4_DoFSCommand('openwindow','museum/sloth'); return false;" alt="Sloth">

  </map>
</p>
