<?php
// Names of all the video sections, and their corresponding titles
// Most sections have one videom so their name maps to their video titles
// Those that have more than one link to a sub-array, within which the name maps each video to its title
//
$sectionnames = array ("beverley" => array( "beverley/activities" => "Activities for budding plant biologists",
											"beverley/why" => "Why become a plant biologist?",
											"beverley/working" => "Working as a plant scientist",
											"beverley/advice" => "Advice about becoming a scientist",
											"beverley/impact" => "The impact of plant research",
											"beverley/future" => "The future of plant research"),

                        "sarah" => array("sarah/advice" => "Advice for budding paleontologists",
										 "sarah/dinosaur" => "Working with dinosaur fossils",
										  "sarah/fossilhunting" => "Fossil hunting",
											"sarah/background" => "How she became a conservator at the museum",
											"sarah/specimens" => "Restoring fossil specimens",
											"sarah/work" => "Her work as the conservator"),

						 "sean" => array("sean/advice" => "Getting involved in conservation",
											"sean/work" => "Working in conservation",
											"sean/conservationUK" => "Conservation on farmland in the UK",
											"sean/background" => "The skills needed",
											"sean/futureAfrica" => "Future conservation work in Africa"),

						 "matt" => array("matt/advice" => "Skills needed for ecotourism",
											"matt/benefits" => "Benefits of ecotourism",
											"matt/work" => "Working in ecotourism",
											"matt/swimwhales" => "Interacting with Minke whales"),



                         "mattw" => array("mattw/research" => "Research on pterosaurs",
											"mattw/studies" => "Why he studies pterosaurs",
											"mattw/flight" => "Pterosaur flight",
											"mattw/phD" => "Why he did a degree and PhD",
                                            "mattw/extinction" => "Why pterosaurs died out"),


	                     "jeremy" => array("jeremy/research" => "Studying how frogs develop",
											"jeremy/frog" => "Working with frog embryos",
											"jeremy/why" => "Why Jeremy became a scientist",
											"jeremy/scientists" => "The image of a scientist",
                                            "jeremy/admires" => "Scientists Jeremy admires",
                                            "jeremy/future" => "What are Jeremy's future career choices"),


	                     "ed" => array("ed/advice" => "Why he became a biologist",
											"ed/studies" => "Research in the tropical rainforest",
											"ed/work" => "Working in the tropical rainforest",
											"ed/changes" => "Changes to the tropical rainforest",
                                            "ed/PhD" => "The personal benefits of doing a PhD",
                                            "ed/future" => "What he would like to do after hi PhD"),


	                     "divya" => array("divya/advice" => "Advice if you want to go to medical school",
											"divya/medistu" => "Being a medical student in Cambridge",
											"divya/lifeatcam" => "Life as a Cambridge University student",
											"divya/background" => "Her route to being a medical student",
                                            "divya/science" => "Scientific breakthroughs"),


                         "annette" => array("annette/degreetophd" => "Moving from a first degree to doing a PhD",
											"annette/phd" => "Why she is studying for a PhD",
											"annette/research" => "Her research in body size in mammals"),


                         "adam" => array("adam/teaching" => "Working as a science teacher",
											"adam/advice" => "Advice on becoming a science teacher",
                                            "adam/bestteachers" => "What makes a good teacher"),


						"whale" => array ("whale1" => "Whale (part 1)",
										  "whale2" => "Whale (part 2)"),

						"monotremes" => array ("echidna" => "Echidna",
						 					   "platypus" => "Platypus"),

						"marsupials" => "Marsupials",
						"insectivores" => "Insectivores",
						"bats" => "Bats",
						"primates" => "Primates",
						"greatapes" => "Great Apes",
						"ungulates" => "Ungulates",
						"carnivores" => "Carnivores",
						"aardvark" => "Aardvark",
						"sloth" => "Sloth",

						"adamsedgwick" => "Adam Sedgwick",
						"intro" => "Introduction",
						"burgess" => "Burgess Shale",
						"carboniferous" => "Carboniferous Period",
						"pleisiosaurus" => "Pleisiosaurus",
						"iguanodon" => "Iguanodon",
						"salamander" => "Cryptobranchus",
						"elephant" => "Deinotherum",
						"hippo" => "Hippopotamus");

?>